Repository janus-idp/backstage-plugins, pull requests merged in 2023-08, with the labels that each got.

#577 feat(topology): show only latest 3 pods/plrs in node sidebar
  plugins/topology/src/__fixtures__/1-tektonResources.ts
  plugins/topology/src/__fixtures__/workloadNodeData.ts
  plugins/topology/src/common/components/ResourceName.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PLRlist.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.test.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanelItem.css
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPaneltem.tsx
  plugins/topology/src/const.ts
  plugins/topology/src/utils/pipeline-utils.ts
  plugins/topology/src/utils/resource-utils.ts
Labels: kind/feature

#615 feat(topology): add runtime icon to topology node
  plugins/topology/README.md
  plugins/topology/src/components/Graph/WorkloadNode.tsx
  plugins/topology/src/components/Topology/TopologyComponent.tsx
  plugins/topology/src/components/Topology/TopologyToolbar.tsx
  plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx
  plugins/topology/src/const.ts
  plugins/topology/src/data-transforms/data-transformer.ts
  plugins/topology/src/hooks/FilterContext.ts
  plugins/topology/src/hooks/useFilterContextValues.ts
  plugins/topology/src/imgs/logos/angularjs.svg
  plugins/topology/src/imgs/logos/apache.svg
  plugins/topology/src/imgs/logos/django.svg
  plugins/topology/src/imgs/logos/dotnet.svg
  plugins/topology/src/imgs/logos/drupal.svg
  plugins/topology/src/imgs/logos/go-gopher.svg
  plugins/topology/src/imgs/logos/golang.svg
  plugins/topology/src/imgs/logos/grails.svg
  plugins/topology/src/imgs/logos/jboss.svg
  plugins/topology/src/imgs/logos/jruby.svg
  plugins/topology/src/imgs/logos/js.svg
  plugins/topology/src/imgs/logos/nginx.svg
  plugins/topology/src/imgs/logos/nodejs.svg
  plugins/topology/src/imgs/logos/openjdk.svg
  plugins/topology/src/imgs/logos/perl.svg
  plugins/topology/src/imgs/logos/phalcon.svg
  plugins/topology/src/imgs/logos/php.svg
  plugins/topology/src/imgs/logos/python.svg
  plugins/topology/src/imgs/logos/quarkus.svg
  plugins/topology/src/imgs/logos/rails.svg
  plugins/topology/src/imgs/logos/redis.svg
  plugins/topology/src/imgs/logos/rh-spring-boot.svg
  plugins/topology/src/imgs/logos/ruby.svg
  plugins/topology/src/imgs/logos/rust.svg
  plugins/topology/src/imgs/logos/spring-boot.svg
  plugins/topology/src/imgs/logos/spring.svg
  plugins/topology/src/types/types.ts
  plugins/topology/src/utils/icons.ts
  plugins/topology/src/utils/topology-utils.ts
Labels: kind/feature

#606 docs(tekton): updated images
  plugins/tekton/README.md
  plugins/tekton/images/tekton-plugin-user1.png
  plugins/tekton/images/tekton-plugin-user2.png
  plugins/tekton/images/tekton-plugin-user3.png
Labels: kind/documentation

#683 docs: acr plugin documentation
  plugins/acr/README.md
  plugins/acr/images/acr-plugin-user1.png
Labels: plugin/acr, kind/documentation
