Repository janus-idp/backstage-plugins, pull requests merged in 2024-05, with the labels that each got.

#1596 docs(servicenow): fix typo in the service now documentation
  plugins/servicenow-actions/README.md
Labels: approved, lgtm

#1568 chore(owners): add NA Roster
  OWNERS
Labels: lgtm

#1595 fix(orchestrator): disable sorting ID column in workflow runs table
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
Labels: approved, lgtm

#1598 fix(cli): allow retrieving scalprum config from an external file in `export-dynamic-plugin`.
  packages/cli/src/commands/export-dynamic-plugin/frontend.ts
  packages/cli/src/commands/index.ts
Labels: approved, lgtm

#1603 fix(cli): completely removing the requirement for `app-config` when exporting fronted plugins to dynamic.
  packages/cli/src/commands/export-dynamic-plugin/frontend.ts
  packages/cli/src/lib/builder/buildScalprumPlugin.ts
Labels: approved, lgtm

#1452 fix(kiali): remove IstioConfig extra, Fix links and add kiali control
  plugins/kiali-backend/__fixtures__/data/config/status.json
  plugins/kiali-backend/src/clients/KialiAPIConnector.test.ts
  plugins/kiali-backend/src/clients/KialiAPIConnector.ts
  plugins/kiali-backend/src/clients/fetch.test.ts
  plugins/kiali-backend/src/clients/fetch.ts
  plugins/kiali-backend/src/kiali_supported.json
  plugins/kiali-backend/src/service/router.test.ts
  plugins/kiali-backend/src/service/router.ts
  plugins/kiali/DEVELOPMENT.md
  plugins/kiali/dev/index.tsx
  plugins/kiali/package.json
  plugins/kiali/playwright.config.ts
  plugins/kiali/src/Router.tsx
  plugins/kiali/src/components/BreadcrumbView/BreadcrumbView.tsx
  plugins/kiali/src/components/DetailDescription/DetailDescription.tsx
  plugins/kiali/src/components/Link/IstioObjectLink.tsx
  plugins/kiali/src/components/Link/ServiceLink.tsx
  plugins/kiali/src/components/Link/WorkloadLink.tsx
  plugins/kiali/src/components/Router.tsx
  plugins/kiali/src/components/VirtualList/Renderers.tsx
  plugins/kiali/src/pages/AppDetails/AppDetailsPage.tsx
  plugins/kiali/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  plugins/kiali/src/pages/Kiali/KialiHelper.tsx
  plugins/kiali/src/pages/Kiali/KialiNoAnnotation.tsx
  plugins/kiali/src/pages/Kiali/KialiNoResources.tsx
  plugins/kiali/src/pages/Overview/ListView/ListViewPage.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceDetailsPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadInfo.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
  plugins/kiali/src/plugin.ts
  plugins/kiali/src/routes.ts
  plugins/kiali/src/store/KialiProvider.tsx
  plugins/kiali/src/utils/entityFilter.ts
  plugins/kiali/src/utils/janusLinks.tsx
  plugins/kiali/tests/kiali.spec.ts
Labels: approved, lgtm

#1528 feat(ocm)!: add basic permissions to ocm backend plugin
  plugins/ocm-backend/dev/index.ts
  plugins/ocm-backend/package.json
  plugins/ocm-backend/src/service/router.test.ts
  plugins/ocm-backend/src/service/router.ts
  plugins/ocm-common/package.json
  plugins/ocm-common/src/index.ts
  plugins/ocm-common/src/permissions.ts
  plugins/ocm-common/src/types.ts
  plugins/ocm/README.md
  plugins/ocm/package.json
  plugins/ocm/src/components/ClusterAvailableResourcesCard/ClusterAvailableResourcesCard.test.tsx
  plugins/ocm/src/components/ClusterAvailableResourcesCard/ClusterAvailableResourcesCard.tsx
  plugins/ocm/src/components/ClusterInfoCard/ClusterInfoCard.test.tsx
  plugins/ocm/src/components/ClusterInfoCard/ClusterInfoCard.tsx
  plugins/ocm/src/components/ClusterStatusPage/ClusterStatusPage.tsx
  yarn.lock
Labels: approved, lgtm

#1612 feat(orchestrator): make the internal sonata podman compatible
  plugins/orchestrator-backend/src/service/DevModeService.ts
Labels: approved, lgtm

#1611 fix(ocm): update ocm frontend plugin readme
  plugins/ocm-backend/src/helpers/parser.ts
  plugins/ocm/README.md
  plugins/rbac-backend/docs/permissions.md
Labels: approved, lgtm

#1586 fix(kiali): remove kiali-common from package.
  plugins/kiali-backend/package.json
  yarn.lock
Labels: approved, lgtm

#1614 fix(orchestrator): disabled MUI table thirdSortClick
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
  plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx
Labels: approved, lgtm

#1540 feat(argocd): add argocd deployment lifecycle and summary component
  plugins/argocd/README.md
  plugins/argocd/config.d.ts
  plugins/argocd/dev/__data__/applications.ts
  plugins/argocd/dev/__data__/config.ts
  plugins/argocd/dev/__data__/entity.ts
  plugins/argocd/dev/__data__/index.ts
  plugins/argocd/dev/__data__/revision.ts
  plugins/argocd/dev/index.tsx
  plugins/argocd/package.json
  plugins/argocd/src/api/__tests__/index.test.ts
  plugins/argocd/src/api/index.ts
  plugins/argocd/src/components/AppStatus/AppHealthStatus.tsx
  plugins/argocd/src/components/AppStatus/AppSyncStatus.tsx
  plugins/argocd/src/components/AppStatus/StatusHeading.tsx
  plugins/argocd/src/components/AppStatus/StatusIcons.tsx
  plugins/argocd/src/components/AppStatus/__tests__/AppHealthStatus.test.tsx
  plugins/argocd/src/components/AppStatus/__tests__/AppSyncStatus.test.tsx
  plugins/argocd/src/components/AppStatus/__tests__/StatusHeading.test.tsx
  plugins/argocd/src/components/AppStatus/__tests__/StatusIcons.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleHeader.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleCard.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleDrawer.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleHeader.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/index.ts
  plugins/argocd/src/components/DeploymentSummary/DeploymentSummary.tsx
  plugins/argocd/src/components/DeploymentSummary/__tests__/DeploymentSummary.test.tsx
  plugins/argocd/src/components/DeploymentSummary/index.ts
  plugins/argocd/src/components/ExampleComponent/ExampleComponent.test.tsx
  plugins/argocd/src/components/ExampleComponent/ExampleComponent.tsx
  plugins/argocd/src/components/ExampleComponent/index.ts
  plugins/argocd/src/components/ExampleFetchComponent/ExampleFetchComponent.test.tsx
  plugins/argocd/src/components/ExampleFetchComponent/ExampleFetchComponent.tsx
  plugins/argocd/src/components/ExampleFetchComponent/index.ts
  plugins/argocd/src/hooks/__tests__/useApplications.test.ts
  plugins/argocd/src/hooks/__tests__/useArgocdConfig.test.tsx
  plugins/argocd/src/hooks/useApplications.ts
  plugins/argocd/src/hooks/useArgocdConfig.ts
  plugins/argocd/src/index.ts
  plugins/argocd/src/plugin.test.ts
  plugins/argocd/src/plugin.test.tsx
  plugins/argocd/src/plugin.ts
  plugins/argocd/src/types.ts
  plugins/argocd/src/utils/__tests__/isArgocdConfigured.test.ts
  plugins/argocd/src/utils/__tests__/utils.test.ts
  plugins/argocd/src/utils/isArgocdConfigured.ts
  plugins/argocd/src/utils/utils.ts
  yarn.lock
Labels: approved, lgtm

#1617 fix: sync lockfile
  yarn.lock
Labels: approved, lgtm

#1616 test(argocd): add playwright dev mode tests
  plugins/argocd/dev/__data__/applications.ts
  plugins/argocd/dev/__data__/config.ts
  plugins/argocd/package.json
  plugins/argocd/playwright.config.ts
  plugins/argocd/tests/argocd.spec.ts
  plugins/argocd/tests/utils.ts
Labels: approved, lgtm

#1565 feat(kiali): add card for resources
  plugins/kiali/dev/index.tsx
  plugins/kiali/src/components/DetailDescription/DetailDescription.tsx
  plugins/kiali/src/components/Drawers/AppDetailsDrawer.tsx
  plugins/kiali/src/components/Drawers/ServiceDetailsDrawer.tsx
  plugins/kiali/src/components/Drawers/WorkloadDetailsDrawer.tsx
  plugins/kiali/src/components/VirtualList/Renderers.tsx
  plugins/kiali/src/components/VirtualList/VirtualList.tsx
  plugins/kiali/src/dynamic/EntityKialiResourcesCard.tsx
  plugins/kiali/src/dynamic/KialiContext.tsx
  plugins/kiali/src/helpers/namespaces.ts
  plugins/kiali/src/index.ts
  plugins/kiali/src/pages/AppDetails/AppDescription.tsx
  plugins/kiali/src/pages/AppDetails/AppInfo.tsx
  plugins/kiali/src/pages/AppList/AppListPage.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceDescription.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceInfo.tsx
  plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadInfo.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
  plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
  plugins/kiali/src/plugin.ts
  plugins/kiali/src/types/ErrorRate/ErrorRate.ts
  plugins/kiali/src/types/Health.ts
  plugins/kiali/src/types/types.ts
  plugins/kiali/tests/entityResources.spec.ts
Labels: approved, lgtm

#1501 fix(rbac): implement ability to disable rbac-backend plugin
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: approved, lgtm

#1602 docs(orchestrator): align readme file with main
  plugins/orchestrator/README.md
Labels: approved, lgtm

#1618 fix(argocd): fix argocd configurations visibility
  plugins/argocd/config.d.ts
Labels: approved, lgtm

#1620 fix(argocd): fix sonarcloud lint warnings in argocd plugin
  packages/backend/src/plugins/argocd.ts
  plugins/argocd/dev/__data__/applications.ts
  plugins/argocd/src/components/AppStatus/AppNamespace.tsx
  plugins/argocd/src/components/AppStatus/__tests__/AppNamespace.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
  plugins/argocd/tests/argocd.spec.ts
Labels: approved, lgtm

#1588 feat(rbac): support for adding conditional permissions
  packages/backend/package.json
  plugins/rbac/dev/index.tsx
  plugins/rbac/package.json
  plugins/rbac/src/__fixtures__/mockPermissionPolicies.ts
  plugins/rbac/src/__fixtures__/mockTransformedConditionRules.ts
  plugins/rbac/src/api/RBACBackendClient.ts
  plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
  plugins/rbac/src/components/ConditionalAccess/CustomArrayField.tsx
  plugins/rbac/src/components/ConditionalAccess/RulesDropdownOption.tsx
  plugins/rbac/src/components/ConditionalAccess/const.ts
  plugins/rbac/src/components/ConditionalAccess/types.ts
  plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.test.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/components/CreateRole/PoliciesCheckboxGroup.tsx
  plugins/rbac/src/components/CreateRole/ReviewStep.tsx
  plugins/rbac/src/components/CreateRole/RoleForm.tsx
  plugins/rbac/src/components/CreateRole/const.ts
  plugins/rbac/src/components/CreateRole/types.ts
  plugins/rbac/src/hooks/useConditionRules.test.ts
  plugins/rbac/src/hooks/useConditionRules.ts
  plugins/rbac/src/types.ts
  plugins/rbac/src/utils/create-role-utils.test.ts
  plugins/rbac/src/utils/create-role-utils.ts
  plugins/rbac/tests/rbac.spec.ts
  yarn.lock
Labels: approved, lgtm

#1621 docs(kiali): update rhdh docs
  plugins/kiali/RHDH.md
  plugins/kiali/app-config.janus-idp.yaml
  plugins/kiali/images/rhdh/RHDH_kiali_page_istio_config.png
  plugins/kiali/images/rhdh/RHDH_kiali_page_overview.png
  plugins/kiali/images/rhdh/RHDH_kiali_page_workloads.png
  plugins/kiali/images/rhdh/RHDH_kiali_page_workloads_details.png
  plugins/kiali/images/rhdh/RHDH_kiali_resources_card.png
  plugins/kiali/images/rhdh/RHDH_kiali_resources_card_details.png
Labels: approved, lgtm

#1625 chore(codeowners): clean up codeowners file
  .github/CODEOWNERS
Labels: approved, lgtm

#1567 feat(scaffolder): create custom action for scaffolder templates
  plugins/scaffolder-annotator-action/.eslintrc.js
  plugins/scaffolder-annotator-action/README.md
  plugins/scaffolder-annotator-action/dist-dynamic/package.json
  plugins/scaffolder-annotator-action/dist-dynamic/yarn.lock
  plugins/scaffolder-annotator-action/examples/templates/01-scaffolder-template.yaml
  plugins/scaffolder-annotator-action/package.json
  plugins/scaffolder-annotator-action/src/actions/annotator/annotator.test.ts
  plugins/scaffolder-annotator-action/src/actions/annotator/annotator.ts
  plugins/scaffolder-annotator-action/src/actions/annotator/index.ts
  plugins/scaffolder-annotator-action/src/actions/annotator/mocks/catalog-info.yaml
  plugins/scaffolder-annotator-action/src/actions/customActions/createScaffoldedFromAction.ts
  plugins/scaffolder-annotator-action/src/actions/customActions/createTimestampAction.ts
  plugins/scaffolder-annotator-action/src/actions/customActions/index.ts
  plugins/scaffolder-annotator-action/src/actions/index.ts
  plugins/scaffolder-annotator-action/src/alpha.ts
  plugins/scaffolder-annotator-action/src/dynamic/index.ts
  plugins/scaffolder-annotator-action/src/index.ts
  plugins/scaffolder-annotator-action/src/module.ts
  plugins/scaffolder-annotator-action/src/utils/convertLabelsToObject.ts
  plugins/scaffolder-annotator-action/src/utils/getCurrentTimestamp.test.ts
  plugins/scaffolder-annotator-action/src/utils/getCurrentTimestamp.ts
  plugins/scaffolder-annotator-action/src/utils/getObjectToAnnotate.ts
  plugins/scaffolder-annotator-action/src/utils/resolveSpec.ts
  plugins/scaffolder-annotator-action/tsconfig.json
  plugins/scaffolder-annotator-action/turbo.json
  yarn.lock
Labels: approved, lgtm

#1608 chore: use the new Events service in the Showcase
  packages/backend/src/index.ts
  packages/backend/src/types.ts
  plugins/orchestrator-backend/dev/index.ts
  plugins/orchestrator-backend/src/run.ts
Labels: approved, lgtm

#1632 fix(rbac)!: remove token manager for auth service
  plugins/rbac-backend/README.md
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/plugin.ts
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.test.ts
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
  plugins/rbac-backend/src/role-manager/role-manager.test.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: approved

#1631 chore(owners): remove OWNERS files from orchestrator plugins
  .github/CODEOWNERS
  plugins/notifications-backend/OWNERS
  plugins/notifications/OWNERS
  plugins/orchestrator-backend/OWNERS
  plugins/orchestrator-common/OWNERS
  plugins/orchestrator-swf-editor-envelope/OWNERS
  plugins/orchestrator/OWNERS
Labels: approved, lgtm

#1634 chore(owners): remove OWNERS files from kiali, update CODEOWNERS
  .github/CODEOWNERS
  plugins/kiali-backend/OWNERS
  plugins/kiali/OWNERS
Labels: approved

#1636 chore(owners): remove OWNERS files from devex and rhtap plugins
  plugins/analytics-module-matomo/OWNERS
  plugins/argocd/OWNERS
  plugins/feedback-backend/OWNERS
  plugins/feedback/OWNERS
  plugins/quay/OWNERS
  plugins/tekton/OWNERS
Labels: approved, lgtm

#1639 fix(orchestrator): typos mentioning OpenShift
  plugins/orchestrator/README.md
  plugins/orchestrator/docs/quickstart.md
Labels: approved, lgtm

#1642 fix(kiali): removing unnecessary afterAll hook
  plugins/kiali/tests/kiali.spec.ts
Labels: lgtm

#1647 fix(argocd): make refreshInterval configuration as optional
  plugins/argocd/config.d.ts
Labels: approved, lgtm

#1646 feat(feedback): use backstage auth service in backend plugin
  plugins/feedback-backend/README.md
  plugins/feedback-backend/dist-dynamic/package.json
  plugins/feedback-backend/dist-dynamic/yarn.lock
  plugins/feedback-backend/package.json
  plugins/feedback-backend/src/database/feedbackStore.ts
  plugins/feedback-backend/src/index.ts
  plugins/feedback-backend/src/plugin.ts
  plugins/feedback-backend/src/service/emails.ts
  plugins/feedback-backend/src/service/router.test.ts
  plugins/feedback-backend/src/service/router.ts
  plugins/feedback-backend/src/service/standaloneServer.ts
  plugins/feedback/app-config.janus-idp.yaml
  plugins/feedback/src/api/index.ts
  plugins/feedback/src/plugin.ts
  yarn.lock
Labels: approved, lgtm

#1587 feat(rbac): implement a file watcher for csv reloads
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policies-actions.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/entityref-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/error-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/permission-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/role-entityref-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/valid-csv/simple-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/valid-csv/updated-rbac-policy.csv
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/file-permissions/csv.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-validation.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  yarn.lock
Labels: approved, lgtm

#1645 chore(tests): do not run unit tests in parallel
  package.json
  turbo.json
Labels: approved, lgtm

#1619 fix(rbac): fix sonar cloud issues for rbac-backend plugin
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
Labels: approved, lgtm

#1480 feat(deps): use RHDH themes in the backstage app and dev pages
  packages/app/package.json
  packages/app/src/App.tsx
  plugins/acr/dev/index.tsx
  plugins/acr/package.json
  plugins/analytics-module-matomo/dev/index.tsx
  plugins/analytics-module-matomo/package.json
  plugins/analytics-provider-segment/dev/index.tsx
  plugins/analytics-provider-segment/package.json
  plugins/argocd/dev/index.tsx
  plugins/argocd/package.json
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/package.json
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/package.json
  plugins/feedback/dev/index.tsx
  plugins/feedback/package.json
  plugins/jfrog-artifactory/dev/index.tsx
  plugins/jfrog-artifactory/package.json
  plugins/kiali/dev/index.tsx
  plugins/kiali/package.json
  plugins/matomo/dev/index.tsx
  plugins/matomo/package.json
  plugins/nexus-repository-manager/dev/index.tsx
  plugins/nexus-repository-manager/package.json
  plugins/notifications/dev/index.tsx
  plugins/notifications/package.json
  plugins/ocm/dev/index.tsx
  plugins/ocm/package.json
  plugins/openshift-image-registry/dev/index.tsx
  plugins/openshift-image-registry/package.json
  plugins/orchestrator/dev/index.tsx
  plugins/orchestrator/package.json
  plugins/quay/dev/index.tsx
  plugins/quay/package.json
  plugins/rbac/dev/index.tsx
  plugins/rbac/package.json
  plugins/tekton/dev/index.tsx
  plugins/tekton/package.json
  plugins/topology/dev/index.tsx
  plugins/topology/package.json
  plugins/web-terminal/dev/index.tsx
  plugins/web-terminal/package.json
  yarn.lock
Labels: approved, lgtm

#1640 test(orchestrator): add OrchestratorClient unit tests
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/utils/UrlUtils.test.ts
Labels: approved, lgtm

#1637 chore(renovate): update config to create team specific PRs
  .github/renovate.json
Labels: lgtm

#1628 feat(rbac): support for updating/deleting conditional permissions
  plugins/rbac/dev/index.tsx
  plugins/rbac/src/__fixtures__/mockConditions.ts
  plugins/rbac/src/__fixtures__/mockFormValues.tsx
  plugins/rbac/src/api/RBACBackendClient.ts
  plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
  plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx
  plugins/rbac/src/components/CreateRole/EditRolePage.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/components/CreateRole/RoleForm.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
  plugins/rbac/src/components/RolesList/DeleteRoleDialog.test.tsx
  plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx
  plugins/rbac/src/hooks/usePermissionPolicies.ts
  plugins/rbac/src/types.ts
  plugins/rbac/src/utils/create-role-utils.test.ts
  plugins/rbac/src/utils/create-role-utils.ts
  plugins/rbac/src/utils/rbac-utils.test.ts
  plugins/rbac/src/utils/rbac-utils.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: approved, lgtm

#1662 chore(orchestrator): point the README at the new backstage-orchestrator-workflows repo
  plugins/orchestrator/README.md
Labels: approved, lgtm

#1663 docs(orchestrator): removes instructions related to the editor
  plugins/orchestrator-backend/app-config.janus-idp.yaml
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator-swf-editor-envelope/README.md
  plugins/orchestrator/README.md
Labels: approved, lgtm

#1664 docs(orchestrator): removes instructions related to the editor
  plugins/orchestrator-backend/app-config.janus-idp.yaml
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator-swf-editor-envelope/README.md
  plugins/orchestrator/README.md
Labels: approved, lgtm

#1668 fix(lint): ignore lint rules on generated code
  plugins/servicenow-actions/.eslintrc.js
Labels: approved, lgtm

#1669 chore(deps): rhdh minor dep updates
  packages/cli/package.json
  plugins/bulk-import/package.json
  plugins/rbac/package.json
  yarn.lock
Labels: approved, lgtm

#1650 fix(orchestrator): remove the need of react dev dependencies
  package.json
  plugins/orchestrator/package.json
  yarn.lock
Labels: approved, lgtm

#1692 fix(quay): remove unuseful link
  plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
  plugins/quay/src/components/QuayRepository/QuayRepository.tsx
Labels: approved, lgtm

#1681 fix(orchestrator): fixes many security-related issues
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStep.ts
Labels: approved, lgtm

#1591 feat: add custom processor module to add ScaffoldedFrom relation
  plugins/catalog-backend-module-scaffolder-relation-processor/.eslintrc.js
  plugins/catalog-backend-module-scaffolder-relation-processor/README.md
  plugins/catalog-backend-module-scaffolder-relation-processor/app-config.janus-idp.yaml
  plugins/catalog-backend-module-scaffolder-relation-processor/config.d.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/package.json
  plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/yarn.lock
  plugins/catalog-backend-module-scaffolder-relation-processor/docs/example-images/scaffoldedFromGraphView.png
  plugins/catalog-backend-module-scaffolder-relation-processor/docs/example-images/scaffoldedFromYAMLView.png
  plugins/catalog-backend-module-scaffolder-relation-processor/docs/example-images/scaffolderOfGraphView.png
  plugins/catalog-backend-module-scaffolder-relation-processor/docs/example-images/scaffolderOfYAMLView.png
  plugins/catalog-backend-module-scaffolder-relation-processor/package.json
  plugins/catalog-backend-module-scaffolder-relation-processor/src/ScaffolderRelationEntityProcessor.test.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/ScaffolderRelationEntityProcessor.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/alpha.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/dynamic/index.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/index.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/module.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/relations.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/src/types.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/tsconfig.json
  plugins/catalog-backend-module-scaffolder-relation-processor/turbo.json
  yarn.lock
Labels: approved, lgtm

#1599 feat(orchestrator): add permissions to orchestrator plugin
  plugins/orchestrator-backend/dev/index.ts
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/OrchestratorPlugin.ts
  plugins/orchestrator-backend/src/routerWrapper/index.ts
  plugins/orchestrator-backend/src/service/DevModeService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/src/index.ts
  plugins/orchestrator-common/src/permissions.ts
  plugins/orchestrator/docs/Permissions.md
  plugins/orchestrator/docs/rbac-policy.csv
  plugins/orchestrator/package.json
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/plugin.ts
Labels: approved, lgtm

#1704 fix(orchestrator): fix the common package reference version
  plugins/orchestrator-backend/package.json
  plugins/orchestrator/package.json
Labels: approved, lgtm

#1696 fix(deps): upgrade devex plugins to mui v5
  plugins/feedback-backend/dist-dynamic/package.json
  plugins/feedback-backend/dist-dynamic/yarn.lock
  plugins/feedback-backend/package.json
  plugins/feedback-backend/src/dynamic/inedx.ts
  plugins/feedback/package.json
  plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
  plugins/feedback/src/components/EntityFeedbackPage/CustomEmptyState/CustomEmptyState.tsx
  plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.test.tsx
  plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
  plugins/feedback/src/components/FeedbackDetailsModal/FeedbackDetailsModal.tsx
  plugins/feedback/src/components/FeedbackTable/FeedbackTable.tsx
  plugins/feedback/src/components/GlobalFeedbackPage/GlobalFeedbackPage.tsx
  plugins/feedback/src/components/OpcFeedbackComponent/OpcFeedbackComponent.tsx
  plugins/feedback/src/index.ts
  plugins/matomo-backend/README.md
  plugins/matomo-backend/app-config.janus-idp.yaml
  plugins/matomo-backend/config.d.ts
  plugins/matomo-backend/src/plugin.ts
  plugins/matomo-backend/src/service/router.ts
  plugins/matomo-backend/src/service/standaloneServer.ts
  plugins/matomo/README.md
  plugins/matomo/package.json
  plugins/matomo/src/api/index.ts
  plugins/matomo/src/components/MatomoPage/MatomoPage.tsx
  plugins/matomo/src/components/MatomoPage/StatsCard.tsx
  plugins/matomo/src/plugin.ts
  yarn.lock
Labels: lgtm, team/devex

#1697 chore(rbac-common): add Unauthorized error
  plugins/rbac-common/package.json
  plugins/rbac-common/src/types.ts
Labels: approved, lgtm

#1707 fix(rbac): fix mui autocomplete related warnings
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
Labels: approved, lgtm

#1622 feat(audit-log): add common audit-log package
  .github/renovate.json
  plugins/audit-log-node/.eslintrc.js
  plugins/audit-log-node/README.md
  plugins/audit-log-node/package.json
  plugins/audit-log-node/src/DefaultAuditLogger.test.ts
  plugins/audit-log-node/src/DefaultAuditLogger.ts
  plugins/audit-log-node/src/index.ts
  plugins/audit-log-node/src/setupTests.ts
  plugins/audit-log-node/src/types.ts
  plugins/audit-log-node/tsconfig.json
  plugins/audit-log-node/turbo.json
  yarn.lock
Labels: approved, lgtm

#1649 chore(orchestrator): add openapi client generation support
  plugins/orchestrator-common/.eslintrc.js
  plugins/orchestrator-common/.gitignore
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/api/models/schema.ts
  plugins/orchestrator-common/src/generated/docs/index.adoc/.openapi-generator-ignore
  plugins/orchestrator-common/src/generated/docs/index.adoc/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/index.adoc/.openapi-generator/VERSION
  plugins/orchestrator-common/src/generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/index.ts
  plugins/orchestrator-common/src/openapi/types.ts
  plugins/orchestrator-common/turbo.json
Labels: lgtm

#1717 fix(orchestrator): fixed broken workflow viewer
  plugins/orchestrator-backend/src/OrchestratorPlugin.ts
Labels: lgtm

#1718 chore(audit-log): change package to public
  plugins/audit-log-node/package.json
Labels: approved, lgtm

#1710 chore(orchestrator): update generation common
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/models/schema.ts
  plugins/orchestrator-common/src/index.ts
  plugins/orchestrator-common/src/openapi/types.ts
  plugins/orchestrator-common/turbo.json
Labels: lgtm

#1719 chore(topology-common): change package to public
  plugins/topology-common/package.json
Labels: approved, lgtm

#1722 fix(orchestrator): temporarily disable plugins/orchestrator-swf-editor-envelope build
  plugins/orchestrator-swf-editor-envelope/package.json
  plugins/orchestrator-swf-editor-envelope/scripts/build
Labels: approved, lgtm

#1723 chore(orchestrator): add dependency to orchestrator-common in turbo
  plugins/orchestrator-backend/turbo.json
Labels: approved, lgtm

#1699 fix(rbac): conditional access form validation
  plugins/rbac/src/__fixtures__/mockConditionRules.ts
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
  plugins/rbac/src/components/ConditionalAccess/CustomArrayField.tsx
Labels: approved, lgtm

#1712 fix(rbac): enable save on remove-all button click
  plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.test.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
Labels: approved, lgtm

#1724 chore(orchestrator): add dependency to common in orchestrator turbo
  plugins/orchestrator/turbo.json
Labels: lgtm

#1725 chore(orchestrator): add genenerated client
  plugins/orchestrator-backend/turbo.json
  plugins/orchestrator-common/.gitignore
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/client/core/ApiError.ts
  plugins/orchestrator-common/src/generated/client/core/ApiRequestOptions.ts
  plugins/orchestrator-common/src/generated/client/core/ApiResult.ts
  plugins/orchestrator-common/src/generated/client/core/CancelablePromise.ts
  plugins/orchestrator-common/src/generated/client/core/OpenAPI.ts
  plugins/orchestrator-common/src/generated/client/core/request.ts
  plugins/orchestrator-common/src/generated/client/core/types.ts
  plugins/orchestrator-common/src/generated/client/index.ts
  plugins/orchestrator-common/src/generated/client/models.ts
  plugins/orchestrator-common/src/generated/client/schemas.ts
  plugins/orchestrator-common/src/generated/client/services.ts
  plugins/orchestrator-common/turbo.json
  plugins/orchestrator/turbo.json
Labels: lgtm

#1721 chore(deps): renovate minor devdep updates
  package.json
  packages/app/package.json
  packages/cli/package.json
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
  packages/storybook/package.json
  plugins/analytics-provider-segment/package.json
  plugins/argocd/src/api/index.ts
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/dynamic-plugins-info/package.json
  plugins/feedback-backend/src/service/router.ts
  plugins/keycloak-backend/package.json
  plugins/keycloak-backend/src/lib/read.ts
  plugins/kiali/src/components/Charts/KChart.tsx
  plugins/kiali/src/components/Metrics/IstioMetrics.tsx
  plugins/kiali/src/components/Metrics/SpanOverlay.ts
  plugins/kiali/src/pages/AppList/AppListPage.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceNetwork.tsx
  plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
  plugins/kiali/src/utils/tracing/TraceTransform.ts
  plugins/kiali/src/utils/tracing/TracingHelper.tsx
  plugins/nexus-repository-manager/src/api/nexus-repository-manager-api-client/nexus-repository-manager-api-client.ts
  plugins/ocm-backend/package.json
  plugins/ocm/package.json
  plugins/rbac-backend/package.json
  plugins/rbac/package.json
  plugins/shared-react/package.json
  plugins/topology/package.json
  plugins/topology/src/components/Graph/WorkloadNode.tsx
  plugins/topology/src/components/Topology/TopologyErrorPanel.tsx
  plugins/topology/src/data-transforms/data-transformer.ts
  plugins/topology/src/utils/pod-resource-utils.ts
  yarn.lock
Labels: approved, lgtm

#1673 feat(rbac): improve conditional policy validation
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/docs/conditions.md
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/validation/condition-validation.test.ts
  plugins/rbac-backend/src/validation/condition-validation.ts
  plugins/rbac-backend/src/validation/policies-validation.test.ts
  plugins/rbac-backend/src/validation/policies-validation.ts
Labels: approved, lgtm

#1727 fix(orchestrator): upgrade to mui v5
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
  plugins/orchestrator/src/components/InfoDialog.stories.tsx
  plugins/orchestrator/src/components/InfoDialog.tsx
  plugins/orchestrator/src/components/OrchestratorIcon.tsx
  plugins/orchestrator/src/components/Paragraph.tsx
  plugins/orchestrator/src/components/Selector.tsx
  plugins/orchestrator/src/components/SubmitButton.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
  plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
  plugins/orchestrator/src/components/WorkflowDialog.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
  plugins/orchestrator/src/components/WorkflowProgressNode.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.stories.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.tsx
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowVariablesViewer.tsx
  plugins/orchestrator/src/components/WorkflowsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
  plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx
  plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
  yarn.lock
Labels: lgtm

#1661 fix(config): enable guest provider by default
  app-config.yaml
Labels: lgtm

#1731 chore(deps): revert dependency on...
  plugins/acr/package.json
  yarn.lock
Labels: approved

#1741 fix(cli): fix entrypoint validation on backstage 1.24.0 and above.
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
Labels: approved, lgtm

#1742 chore(deps): regen yarn lock
  yarn.lock
Labels: approved, lgtm

#1729 chore: adding options to keep legacy behavior in export-dynamic script
  plugins/3scale-backend/package.json
  plugins/aap-backend/package.json
  plugins/acr/package.json
  plugins/analytics-module-matomo/package.json
  plugins/analytics-provider-segment/package.json
  plugins/argocd/package.json
  plugins/bulk-import/package.json
  plugins/catalog-backend-module-scaffolder-relation-processor/package.json
  plugins/dynamic-plugins-info/package.json
  plugins/feedback-backend/package.json
  plugins/feedback/package.json
  plugins/jfrog-artifactory/package.json
  plugins/keycloak-backend/package.json
  plugins/kiali-backend/package.json
  plugins/kiali/package.json
  plugins/kubernetes-actions/package.json
  plugins/matomo-backend/package.json
  plugins/matomo/package.json
  plugins/nexus-repository-manager/package.json
  plugins/notifications-backend/package.json
  plugins/notifications/package.json
  plugins/ocm-backend/package.json
  plugins/ocm/package.json
  plugins/openshift-image-registry/package.json
  plugins/orchestrator-backend/package.json
  plugins/orchestrator/package.json
  plugins/quay-actions/package.json
  plugins/quay/package.json
  plugins/rbac/package.json
  plugins/regex-actions/package.json
  plugins/scaffolder-annotator-action/package.json
  plugins/servicenow-actions/package.json
  plugins/sonarqube-actions/package.json
  plugins/tekton/package.json
  plugins/topology/package.json
  plugins/web-terminal/package.json
  yarn.lock
Labels: approved, lgtm

#1745 chore(deps): fix dependency issues on main
  package.json
  plugins/topology-common/CHANGELOG.md
  plugins/topology-common/package.json
  plugins/topology/package.json
  yarn.lock
Labels: approved, lgtm

#1703 fix(rbac): fix to enable create and edit role buttons on having correct permissions
  plugins/rbac/README.md
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
  plugins/rbac/src/components/CreateRole/CreateRolePage.test.tsx
  plugins/rbac/src/components/CreateRole/CreateRolePage.tsx
  plugins/rbac/src/components/CreateRole/EditRolePage.test.tsx
  plugins/rbac/src/components/CreateRole/EditRolePage.tsx
  plugins/rbac/src/components/RoleOverview/MembersCard.test.tsx
  plugins/rbac/src/components/RoleOverview/MembersCard.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.test.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
  plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
  plugins/rbac/src/hooks/useMembers.ts
  plugins/rbac/src/hooks/useRoles.ts
  plugins/rbac/src/hooks/useSelectedMembers.ts
Labels: approved, lgtm

#1638 fix(scaffolder): update annotator action readme
  plugins/scaffolder-annotator-action/README.md
  plugins/scaffolder-annotator-action/examples/templates/01-scaffolder-template.yaml
  plugins/scaffolder-annotator-action/src/actions/annotator/annotator.test.ts
  plugins/scaffolder-annotator-action/src/actions/annotator/annotator.ts
  plugins/scaffolder-annotator-action/src/dynamic/index.ts
  plugins/scaffolder-annotator-action/src/module.ts
  plugins/scaffolder-annotator-action/src/utils/convertLabelsToObject.ts
  plugins/scaffolder-annotator-action/src/utils/getCurrentTimestamp.test.ts
  plugins/scaffolder-annotator-action/src/utils/getCurrentTimestamp.ts
Labels: approved, lgtm

#1702 fix(rbac): show configure-access cta for existing simple permission policies in edit form
  plugins/rbac/src/types.ts
  plugins/rbac/src/utils/rbac-utils.test.ts
  plugins/rbac/src/utils/rbac-utils.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: approved, lgtm

#1755 fix(rbac): improve criteria toggle button readability on dark themes
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
Labels: approved, lgtm

#1643 feat(rbac)!: improve validation from source
  plugins/rbac-backend/README.md
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/docs/permissions.md
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/error-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/valid-csv/rbac-policy.csv
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/validation/policies-validation.test.ts
  plugins/rbac-backend/src/validation/policies-validation.ts
Labels: approved, lgtm

#1750 chore(deps): update RHDH theme
  packages/app/package.json
  plugins/acr/package.json
  plugins/analytics-module-matomo/package.json
  plugins/analytics-provider-segment/package.json
  plugins/argocd/package.json
  plugins/bulk-import/package.json
  plugins/dynamic-plugins-info/package.json
  plugins/feedback/package.json
  plugins/jfrog-artifactory/package.json
  plugins/kiali/package.json
  plugins/matomo/package.json
  plugins/nexus-repository-manager/package.json
  plugins/notifications/package.json
  plugins/ocm/package.json
  plugins/openshift-image-registry/package.json
  plugins/orchestrator/package.json
  plugins/quay/package.json
  plugins/rbac/package.json
  plugins/tekton/package.json
  plugins/topology/package.json
  plugins/web-terminal/package.json
  scripts/update-rhdh-theme
  yarn.lock
Labels: approved, lgtm
