Repository janus-idp/backstage-plugins, pull requests merged in 2024-08, with the labels that each got.

#1981 chore(metadata): add works-with metadata annotations re: rhsso and keycloak, using npm version notation (RHIDP-2680)
  plugins/keycloak-backend/package.json
Labels: lgtm

#1869 feat(topology): remove usage of k8s plugin from topology & tekton plugins
  plugins/shared-react/package.json
  plugins/shared-react/src/hooks/index.ts
  plugins/shared-react/src/hooks/useKubernetesObjects.ts
  plugins/tekton/README.md
  plugins/tekton/dev/index.tsx
  plugins/tekton/package.json
  plugins/tekton/src/components/PipelineRunList/PipelineRunOutput.tsx
  plugins/tekton/src/components/PipelineRunLogs/PodLogsDownloadLink.tsx
  plugins/tekton/src/hooks/useAllWatchResources.test.ts
  plugins/tekton/src/hooks/useAllWatchResources.ts
  plugins/tekton/src/hooks/usePodContainerLogs.ts
  plugins/tekton/src/hooks/usePodLogsOfPipelineRun.ts
  plugins/tekton/src/hooks/useResourcesClusters.test.ts
  plugins/tekton/src/hooks/useResourcesClusters.ts
  plugins/tekton/src/hooks/useTektonObjectResponse.test.ts
  plugins/tekton/src/hooks/useTektonObjectsResponse.ts
  plugins/tekton/src/plugin.ts
  plugins/tekton/src/types/types.ts
  plugins/topology/README.md
  plugins/topology/dev/index.tsx
  plugins/topology/package.json
  plugins/topology/src/hooks/useAllWatchResources.test.ts
  plugins/topology/src/hooks/useAllWatchResources.ts
  plugins/topology/src/hooks/useK8sObjectsResponse.test.ts
  plugins/topology/src/hooks/useK8sObjectsResponse.ts
  plugins/topology/src/hooks/useK8sResourcesClusters.test.ts
  plugins/topology/src/hooks/useK8sResourcesClusters.ts
  plugins/topology/src/hooks/usePodLogs.ts
  plugins/topology/src/plugin.ts
  plugins/topology/src/types/types.ts
  yarn.lock
Labels: lgtm

#1996 fix(deps): downgrade shared-react in acr
  plugins/acr/package.json
Labels: lgtm

#1917 fix(rbac): log when plugin has no permissions
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
Labels: lgtm

#1908 fix(rbac): add additional validation for permission policies
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/validation/policies-validation.test.ts
  plugins/rbac-backend/src/validation/policies-validation.ts
  plugins/rbac-common/src/types.ts
Labels: lgtm

#2006 fix(topology): bump shared-react dependency
  plugins/topology/package.json
  yarn.lock
Labels: lgtm

#1950 feat(bulk-import): add fields for annotations, labels and spec input
  plugins/bulk-import/src/components/PreviewFile/KeyValueTextField.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/types.ts
  plugins/bulk-import/src/utils/repository-utils.test.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
Labels: lgtm

#2009 fix(acr): revert downgrade of shared-react and janus-cli
  plugins/acr/package.json
  yarn.lock
Labels: lgtm

#1814 feat(rbac): nested condition
  plugins/rbac/src/__fixtures__/mockConditions.ts
  plugins/rbac/src/components/ConditionalAccess/AddNestedConditionButton.tsx
  plugins/rbac/src/components/ConditionalAccess/ComplexConditionRow.tsx
  plugins/rbac/src/components/ConditionalAccess/ComplexConditionRowButtons.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionRule.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.test.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRowFields.tsx
  plugins/rbac/src/components/ConditionalAccess/CriteriaToggleButton.tsx
  plugins/rbac/src/components/ConditionalAccess/const.ts
  plugins/rbac/src/components/ConditionalAccess/types.ts
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/hooks/usePermissionPolicies.test.ts
  plugins/rbac/src/utils/conditional-access-utils.test.ts
  plugins/rbac/src/utils/conditional-access-utils.ts
  plugins/rbac/src/utils/create-role-utils.test.ts
  plugins/rbac/src/utils/create-role-utils.ts
  plugins/rbac/src/utils/rbac-utils.test.ts
  plugins/rbac/src/utils/rbac-utils.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: approved, lgtm

#1847 fix(rbac): implement conditional aliases
  plugins/rbac-backend/docs/conditions.md
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/conditional-aliases/alias-resolver.test.ts
  plugins/rbac-backend/src/conditional-aliases/alias-resolver.ts
  plugins/rbac-backend/src/plugin.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-common/src/types.ts
  yarn.lock
Labels: lgtm

#2020 feat(lightspeed): add api client
  plugins/lightspeed/package.json
  plugins/lightspeed/src/api/LightspeedProxyClient.test.ts
  plugins/lightspeed/src/api/LightspeedProxyClient.ts
  plugins/lightspeed/src/components/LightspeedPage.tsx
  plugins/lightspeed/src/plugin.ts
  yarn.lock
Labels: lgtm

#1922 feat(rbac): conditional policies file watcher
  plugins/rbac-backend/README.md
  plugins/rbac-backend/config.d.ts
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/__fixtures__/data/invalid-conditions/bad-conditions-yaml.yaml
  plugins/rbac-backend/src/__fixtures__/data/invalid-conditions/invalid-yaml.yaml
  plugins/rbac-backend/src/__fixtures__/data/valid-conditions/conditions.yaml
  plugins/rbac-backend/src/__fixtures__/data/valid-conditions/empty-conditions.yaml
  plugins/rbac-backend/src/audit-log/audit-logger.ts
  plugins/rbac-backend/src/database/conditional-storage.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/file-permissions/file-watcher.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  yarn.lock
Labels: lgtm

#2015 fix(bulk-import): set initial value of annotations, labels and specs
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
Labels: lgtm

#2007 feat(orchestrator): fix pagination issue and add filters to instances and overviews
  plugins/orchestrator-backend/src/helpers/queryBuilder.test.ts
  plugins/orchestrator-backend/src/helpers/queryBuilder.ts
  plugins/orchestrator-backend/src/queryBuilder.test.ts
  plugins/orchestrator-backend/src/service/DataIndexService.test.ts
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/v2.test.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-backend/src/types/filters.ts
  plugins/orchestrator-backend/src/types/pagination.test.ts
  plugins/orchestrator-backend/src/types/pagination.ts
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator/src/__fixtures__/fakeWorkflowOverviewList.ts
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
Labels: lgtm

#2032 fix(acr): new credential settings in proxy backend
  plugins/acr/README.md
  plugins/acr/src/api/index.ts
  plugins/acr/src/plugin.ts
  plugins/quay/README.md
Labels: lgtm

#1924 feat(argocd): add support for fetching an application by app name
  plugins/argocd/README.md
  plugins/argocd/dev/index.tsx
  plugins/argocd/src/api/__tests__/index.test.ts
  plugins/argocd/src/api/index.ts
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
  plugins/argocd/src/components/DeploymentSummary/DeploymentSummary.tsx
  plugins/argocd/src/components/DeploymentSummary/__tests__/DeploymentSummary.test.tsx
  plugins/argocd/src/hooks/__tests__/useApplications.test.ts
  plugins/argocd/src/hooks/useApplications.ts
  plugins/argocd/src/utils/__tests__/utils.test.ts
  plugins/argocd/src/utils/isArgocdConfigured.ts
  plugins/argocd/src/utils/utils.ts
Labels: lgtm

#2035 fix(orchestrator): revert upgrade to material 5 to resolve dark theme issues
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
  plugins/orchestrator/src/components/InfoDialog.stories.tsx
  plugins/orchestrator/src/components/InfoDialog.tsx
  plugins/orchestrator/src/components/OrchestratorIcon.tsx
  plugins/orchestrator/src/components/Paragraph.tsx
  plugins/orchestrator/src/components/Selector.tsx
  plugins/orchestrator/src/components/SubmitButton.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
  plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
  plugins/orchestrator/src/components/WorkflowDialog.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
  plugins/orchestrator/src/components/WorkflowProgressNode.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.stories.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.tsx
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowVariablesViewer.tsx
  plugins/orchestrator/src/components/WorkflowsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
  plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx
  plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
  yarn.lock
Labels: lgtm

#2036 fix(orchestrator): remove retrigger button in active state
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm

#1851 feat(quay-common): add permissions support for quay plugin via new plugin quay-common
  plugins/quay-common/.eslintrc.js
  plugins/quay-common/README.md
  plugins/quay-common/package.json
  plugins/quay-common/src/index.ts
  plugins/quay-common/src/permissions.ts
  plugins/quay-common/tsconfig.json
  plugins/quay-common/turbo.json
  plugins/quay/dev/index.tsx
  plugins/quay/package.json
  plugins/quay/src/components/PermissionAlert/PermissionAlert.tsx
  plugins/quay/src/components/QuayRepository/QuayRepository.test.tsx
  plugins/quay/src/components/QuayRepository/QuayRepository.tsx
  plugins/quay/src/components/QuayTagPage/QuayTagPage.test.tsx
  plugins/quay/src/components/QuayTagPage/component.tsx
  plugins/quay/src/hooks/useQuayViewPermission.ts
  plugins/rbac-backend/docs/permissions.md
Labels: approved

#2045 fix(orchestrator): downgrade back to material 4 to solve dark theme incompatibliity
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/JsonTextAreaForm.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
  plugins/orchestrator/src/components/InfoDialog.stories.tsx
  plugins/orchestrator/src/components/InfoDialog.tsx
  plugins/orchestrator/src/components/OrchestratorIcon.tsx
  plugins/orchestrator/src/components/Paragraph.tsx
  plugins/orchestrator/src/components/Selector.tsx
  plugins/orchestrator/src/components/SubmitButton.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
  plugins/orchestrator/src/components/WorkflowDescriptionModal.tsx
  plugins/orchestrator/src/components/WorkflowDialog.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
  plugins/orchestrator/src/components/WorkflowProgressNode.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.tsx
  plugins/orchestrator/src/components/WorkflowRunsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowVariablesViewer.tsx
  plugins/orchestrator/src/components/WorkflowsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
  plugins/orchestrator/src/components/ui/OverrideBackstageTable.tsx
  plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
  yarn.lock
Labels: lgtm, ok-to-test

#2048 fix(orchestrator): remove retrigger button in active state
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm

#1885 chore: add catalog-info yamls
  catalog-info-teams.yaml
  catalog-info.yaml
  packages/cli/catalog-info.yaml
  plugins/3scale-backend/catalog-info.yaml
  plugins/aap-backend/catalog-info.yaml
  plugins/acr/catalog-info.yaml
  plugins/analytics-module-matomo/catalog-info.yaml
  plugins/analytics-provider-segment/catalog-info.yaml
  plugins/argocd-common/catalog-info.yaml
  plugins/argocd/catalog-info.yaml
  plugins/audit-log-node/catalog-info.yaml
  plugins/bulk-import-backend/catalog-info.yaml
  plugins/bulk-import-common/catalog-info.yaml
  plugins/bulk-import/catalog-info.yaml
  plugins/catalog-backend-module-scaffolder-relation-processor/catalog-info.yaml
  plugins/dynamic-plugins-info/catalog-info.yaml
  plugins/feedback-backend/catalog-info.yaml
  plugins/feedback/catalog-info.yaml
  plugins/jfrog-artifactory/catalog-info.yaml
  plugins/keycloak-backend/catalog-info.yaml
  plugins/kiali-backend/catalog-info.yaml
  plugins/kiali/catalog-info.yaml
  plugins/kubernetes-actions/catalog-info.yaml
  plugins/matomo-backend/catalog-info.yaml
  plugins/matomo/catalog-info.yaml
  plugins/nexus-repository-manager/catalog-info.yaml
  plugins/ocm-backend/catalog-info.yaml
  plugins/ocm-common/catalog-info.yaml
  plugins/ocm/catalog-info.yaml
  plugins/openshift-image-registry/catalog-info.yaml
  plugins/orchestrator-backend/catalog-info.yaml
  plugins/orchestrator-common/catalog-info.yaml
  plugins/orchestrator-swf-editor-envelope/catalog-info.yaml
  plugins/orchestrator/catalog-info.yaml
  plugins/quay-actions/catalog-info.yaml
  plugins/quay-common/catalog-info.yaml
  plugins/quay/catalog-info.yaml
  plugins/rbac-backend/catalog-info.yaml
  plugins/rbac-common/catalog-info.yaml
  plugins/rbac-node/catalog-info.yaml
  plugins/rbac/catalog-info.yaml
  plugins/regex-actions/catalog-info.yaml
  plugins/scaffolder-annotator-action/catalog-info.yaml
  plugins/servicenow-actions/catalog-info.yaml
  plugins/shared-react/catalog-info.yaml
  plugins/sonarqube-actions/catalog-info.yaml
  plugins/tekton-common/catalog-info.yaml
  plugins/tekton/catalog-info.yaml
  plugins/topology-common/catalog-info.yaml
  plugins/topology/catalog-info.yaml
  plugins/web-terminal/catalog-info.yaml
Labels: lgtm

#2047 chore: add jerolimov/myself as owner
  OWNERS
Labels: lgtm

#1868 feat(rbac): edit nested conditions
  plugins/rbac/src/__fixtures__/mockConditions.ts
  plugins/rbac/src/components/ConditionalAccess/ConditionsForm.tsx
  plugins/rbac/src/components/ConditionalAccess/ConditionsFormRow.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/utils/conditional-access-utils.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: lgtm

#1907 chore(deps): update rhdh theme package
  packages/app/config.d.ts
  packages/app/package.json
  plugins/acr/dev/index.tsx
  plugins/acr/package.json
  plugins/analytics-module-matomo/dev/index.tsx
  plugins/analytics-module-matomo/package.json
  plugins/analytics-provider-segment/dev/index.tsx
  plugins/analytics-provider-segment/package.json
  plugins/argocd/dev/index.tsx
  plugins/argocd/package.json
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/package.json
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/package.json
  plugins/feedback/dev/index.tsx
  plugins/feedback/package.json
  plugins/jfrog-artifactory/dev/index.tsx
  plugins/jfrog-artifactory/package.json
  plugins/kiali/dev/index.tsx
  plugins/kiali/package.json
  plugins/matomo/dev/index.tsx
  plugins/matomo/package.json
  plugins/nexus-repository-manager/dev/index.tsx
  plugins/nexus-repository-manager/package.json
  plugins/ocm/dev/index.tsx
  plugins/ocm/package.json
  plugins/openshift-image-registry/dev/index.tsx
  plugins/openshift-image-registry/package.json
  plugins/orchestrator/dev/index.tsx
  plugins/orchestrator/package.json
  plugins/quay/dev/index.tsx
  plugins/quay/package.json
  plugins/rbac/package.json
  plugins/tekton/dev/index.tsx
  plugins/tekton/package.json
  plugins/topology/dev/index.tsx
  plugins/topology/package.json
  plugins/web-terminal/dev/index.tsx
  plugins/web-terminal/package.json
  yarn.lock
Labels: lgtm

#2059 fix(cli): support BackendFeatureCompat in export-dynamic cli
  packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts
Labels: lgtm

#2055 feat(orchestrator): add rest endpoint in v2 for fetching input schema
  plugins/orchestrator-backend/package-lock.json
  plugins/orchestrator-backend/src/service/DataInputSchemaService.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
  yarn.lock
Labels: lgtm

#2056 fix(ocm): call OCM only for kubernetes-cluster entities
  plugins/ocm/src/components/ClusterContext/ClusterContext.test.tsx
  plugins/ocm/src/components/ClusterContext/ClusterContext.tsx
Labels: lgtm

#1974 feat(bulk-import): return the total count of repos per org in the `GET /organizations` backend API [RHIDP-3337]
  plugins/bulk-import-backend/api-docs/Models/Organization.md
  plugins/bulk-import-backend/src/openapi.d.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/organizations.ts
  plugins/bulk-import-backend/src/service/router.test.ts
  plugins/bulk-import-backend/src/service/router.ts
  plugins/bulk-import-backend/src/types.ts
Labels: lgtm

#2053 docs(ocm): fix instruction to start dev backend
  plugins/ocm-backend/CONTRIBUTING.md
  plugins/ocm/CONTRIBUTING.md
Labels: lgtm

#2063 fix(deps): update dependency axios to v1.7.4 [security]
  plugins/feedback-backend/dist-dynamic/package.json
  plugins/feedback-backend/dist-dynamic/yarn.lock
  plugins/feedback-backend/package.json
  plugins/feedback/package.json
  plugins/kiali-backend/dist-dynamic/package.json
  plugins/kiali-backend/dist-dynamic/yarn.lock
  plugins/kiali-backend/package.json
  plugins/kiali/package.json
  plugins/matomo/package.json
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-common/package.json
  plugins/orchestrator-form-react/package.json
  plugins/orchestrator/package.json
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/servicenow-actions/dist-dynamic/package.json
  plugins/servicenow-actions/dist-dynamic/yarn.lock
  plugins/servicenow-actions/package.json
  yarn.lock
Labels: lgtm

#2062 chore: add deprecate note to the argocd plugin
  plugins/argocd-common/README.md
  plugins/argocd-common/package.json
  plugins/argocd/README.md
  plugins/argocd/package.json
Labels: lgtm

#2061 fix(nexus): fix asset path for nexus repo
  plugins/nexus-repository-manager/src/api/nexus-repository-manager-api-client/nexus-repository-manager-api-client.ts
  yarn.lock
Labels: lgtm

#1979 feat(bulk-import): perform more dry-run checks in the `POST /imports` backend endpoint [RHIDP-3339]
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/router.test.ts
Labels: lgtm

#2066 chore: remove redundant package-lock.json
  plugins/orchestrator-backend/package-lock.json
Labels: lgtm

#2027 feat(topology): add virtual machine visualization in topology
  plugins/topology/README.md
  plugins/topology/src/__fixtures__/1-deployments.ts
  plugins/topology/src/components/Graph/BaseNode.tsx
  plugins/topology/src/components/Graph/TopologyComponentFactory.tsx
  plugins/topology/src/components/Graph/VMNode.tsx
  plugins/topology/src/components/Topology/TopologyComponent.test.tsx
  plugins/topology/src/components/Topology/TopologyComponent.tsx
  plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx
  plugins/topology/src/const.ts
  plugins/topology/src/data-transforms/data-transformer.test.ts
  plugins/topology/src/data-transforms/data-transformer.ts
  plugins/topology/src/hooks/useSideBar.tsx
  plugins/topology/src/models.ts
  plugins/topology/src/types/vms.ts
  plugins/topology/src/utils/resource-utils.ts
  plugins/topology/src/vm-models.ts
Labels: approved, lgtm

#2043 feat(rbac): add extensions to rbac backend plugin
  plugins/rbac-backend-module-test/.eslintrc.js
  plugins/rbac-backend-module-test/README.md
  plugins/rbac-backend-module-test/app-config.janus-idp.yaml
  plugins/rbac-backend-module-test/config.d.ts
  plugins/rbac-backend-module-test/dist-dynamic/package.json
  plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
  plugins/rbac-backend-module-test/package.json
  plugins/rbac-backend-module-test/src/alpha.ts
  plugins/rbac-backend-module-test/src/dynamic/index.ts
  plugins/rbac-backend-module-test/src/index.ts
  plugins/rbac-backend-module-test/src/module.ts
  plugins/rbac-backend-module-test/src/provider/TestProvider.ts
  plugins/rbac-backend-module-test/test-policy.csv
  plugins/rbac-backend-module-test/tsconfig.json
  plugins/rbac-backend-module-test/turbo.json
  plugins/rbac-backend/README.md
  plugins/rbac-backend/docs/providers.md
  plugins/rbac-backend/src/helper.test.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/plugin.ts
  plugins/rbac-backend/src/providers/connect-providers.test.ts
  plugins/rbac-backend/src/providers/connect-providers.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-common/src/types.ts
  plugins/rbac-node/src/extensions.ts
  plugins/rbac-node/src/types/types.ts
  yarn.lock
Labels: lgtm

#2064 feat(lightspeed): improved chat experience with added context from previous responses
  plugins/lightspeed/package.json
  plugins/lightspeed/src/components/LightspeedPage.tsx
  plugins/lightspeed/src/components/Message.tsx
  yarn.lock
Labels: lgtm

#1890 feat(bulk-import): add permissions support to the backend endpoints [RHIDP-1208]
  plugins/bulk-import-backend/CONTRIBUTING.md
  plugins/bulk-import-backend/README.md
  plugins/bulk-import-backend/api-docs/Apis/ImportApi.md
  plugins/bulk-import-backend/api-docs/Apis/ManagementApi.md
  plugins/bulk-import-backend/api-docs/Apis/OrganizationApi.md
  plugins/bulk-import-backend/api-docs/Apis/RepositoryApi.md
  plugins/bulk-import-backend/api-docs/README.md
  plugins/bulk-import-backend/dev/index.ts
  plugins/bulk-import-backend/package.json
  plugins/bulk-import-backend/src/helpers/auth.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/plugin.test.ts
  plugins/bulk-import-backend/src/plugin.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/router.test.ts
  plugins/bulk-import-backend/src/service/router.ts
  plugins/rbac-backend/docs/permissions.md
Labels: lgtm

#2074 chore(release): fix some issues caused by msr
  plugins/audit-log-node/package.json
  plugins/rbac-backend-module-test/dist-dynamic/package.json
  plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
  plugins/rbac-backend-module-test/package.json
  yarn.lock
Labels: lgtm

#2068 feat(bulk-import): allow skipping the CODEOWNERS dry-run check [RHIDP-3339]
  plugins/bulk-import-backend/api-docs/Models/ImportRequest.md
  plugins/bulk-import-backend/src/openapi.d.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/router.test.ts
Labels: lgtm

#2076 fix(orchestrator): remove unused endpoint /workflows/workflow-id
  plugins/orchestrator-backend/src/service/router.ts
Labels: lgtm

#2078 chore: add deprecate note to the 3scale plugin
  plugins/3scale-backend/README.md
  plugins/3scale-backend/package.json
Labels: lgtm

#2079 fix(orchestrator): add open api documentation to orchestrator readme
  plugins/orchestrator/README.md
Labels: lgtm

#2065 fix(rbac): validate name and namespace of entities
  plugins/rbac-backend/src/validation/policies-validation.test.ts
  plugins/rbac-backend/src/validation/policies-validation.ts
  plugins/rbac/src/api/RBACBackendClient.ts
  plugins/rbac/src/components/CreateRole/AddedMembersTable.test.tsx
  plugins/rbac/src/components/CreateRole/AddedMembersTableColumn.tsx
  plugins/rbac/src/components/CreateRole/RoleForm.tsx
  plugins/rbac/src/components/EditRole.test.tsx
  plugins/rbac/src/components/EditRole.tsx
  plugins/rbac/src/components/RoleOverview/MembersCard.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
  plugins/rbac/src/components/RolesList/RolesListColumns.tsx
  plugins/rbac/src/hooks/useMembers.ts
  plugins/rbac/src/utils/rbac-utils.test.ts
  plugins/rbac/src/utils/rbac-utils.ts
Labels: lgtm

#2086 feat(bulk-import): include more details about PR (title, description, catalog-info content) when fetching import status by repo
  plugins/bulk-import-backend/api-docs/Models/Import_github_pullRequest.md
  plugins/bulk-import-backend/src/openapi.d.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/router.ts
Labels: lgtm

#2088 fix: add more space for workflow description
  plugins/orchestrator/src/components/WorkflowsTable.tsx
Labels: lgtm

#2010 chore(orchestrator): bump default sonata image version to 2024-04-17
  plugins/orchestrator-common/src/constants.ts
Labels: lgtm

#2089 fix(topology): fixes custom styles loading
  plugins/tekton/package.json
  plugins/topology/package.json
Labels: lgtm

#2090 chore(doc): add audit log event naming convention
  plugins/audit-log-node/README.md
Labels: lgtm

#2085 fix(bulk-import): add missing details about repository default branch in `GET /imports` response
  plugins/bulk-import-backend/api-docs/.openapi-generator/FILES
  plugins/bulk-import-backend/api-docs/Models/Import.md
  plugins/bulk-import-backend/api-docs/README.md
  plugins/bulk-import-backend/src/openapi.d.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/router.test.ts
Labels: lgtm

#1966 feat(bulk-import): add audit log to the backend router [RHIDP-2748]
  plugins/bulk-import-backend/README.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/dist-dynamic/yarn.lock
  plugins/bulk-import-backend/package.json
  plugins/bulk-import-backend/src/helpers/auditLogUtils.ts
  plugins/bulk-import-backend/src/helpers/auth.ts
  plugins/bulk-import-backend/src/service/router.ts
Labels: lgtm

#2034 feat(bulk-import): add permission checks in bulk import UI
  plugins/bulk-import/README.md
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/CatalogInfoStatus.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/SelectRepositories.test.tsx
  plugins/bulk-import/src/components/BulkImportPage.test.tsx
  plugins/bulk-import/src/components/BulkImportPage.tsx
  plugins/bulk-import/src/components/BulkImportSidebarItem.test.tsx
  plugins/bulk-import/src/components/BulkImportSidebarItem.tsx
  plugins/bulk-import/src/components/GitAltIcon.tsx
  plugins/bulk-import/src/components/PreviewFile/KeyValueTextField.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.tsx
  plugins/bulk-import/src/components/Repositories/CatalogInfoAction.test.tsx
  plugins/bulk-import/src/components/Repositories/CatalogInfoAction.tsx
  plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListColumns.tsx
  plugins/bulk-import/src/hooks/useAddedRepositories.ts
  plugins/bulk-import/src/mocks/mockData.ts
  plugins/bulk-import/src/plugin.test.ts
  plugins/bulk-import/src/plugin.test.tsx
  plugins/bulk-import/src/types/response-types.ts
  plugins/bulk-import/src/utils/repository-utils.test.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
Labels: lgtm

#2087 fix(rbac): role name update should redirect to correct overview page
  plugins/rbac/src/components/CreateRole/RoleForm.tsx
Labels: lgtm

#2077 chore: update catalog-info.yamls
  catalog-info-teams.yaml
  catalog-info.yaml
  packages/cli/catalog-info.yaml
  plugins/3scale-backend/catalog-info.yaml
  plugins/aap-backend/catalog-info.yaml
  plugins/acr/catalog-info.yaml
  plugins/analytics-module-matomo/catalog-info.yaml
  plugins/analytics-provider-segment/catalog-info.yaml
  plugins/argocd-common/catalog-info.yaml
  plugins/argocd/catalog-info.yaml
  plugins/audit-log-node/catalog-info.yaml
  plugins/bulk-import-backend/catalog-info.yaml
  plugins/bulk-import-common/catalog-info.yaml
  plugins/bulk-import/catalog-info.yaml
  plugins/catalog-backend-module-scaffolder-relation-processor/catalog-info.yaml
  plugins/dynamic-plugins-info/catalog-info.yaml
  plugins/feedback-backend/catalog-info.yaml
  plugins/feedback/catalog-info.yaml
  plugins/jfrog-artifactory/catalog-info.yaml
  plugins/keycloak-backend/catalog-info.yaml
  plugins/kiali-backend/catalog-info.yaml
  plugins/kiali/catalog-info.yaml
  plugins/kubernetes-actions/catalog-info.yaml
  plugins/matomo-backend/catalog-info.yaml
  plugins/matomo/catalog-info.yaml
  plugins/nexus-repository-manager/catalog-info.yaml
  plugins/ocm-backend/catalog-info.yaml
  plugins/ocm-common/catalog-info.yaml
  plugins/ocm/catalog-info.yaml
  plugins/openshift-image-registry/catalog-info.yaml
  plugins/orchestrator-backend/catalog-info.yaml
  plugins/orchestrator-common/catalog-info.yaml
  plugins/orchestrator-swf-editor-envelope/catalog-info.yaml
  plugins/orchestrator/catalog-info.yaml
  plugins/quay-actions/catalog-info.yaml
  plugins/quay-common/catalog-info.yaml
  plugins/quay/catalog-info.yaml
  plugins/rbac-backend/catalog-info.yaml
  plugins/rbac-common/catalog-info.yaml
  plugins/rbac-node/catalog-info.yaml
  plugins/rbac/catalog-info.yaml
  plugins/regex-actions/catalog-info.yaml
  plugins/scaffolder-annotator-action/catalog-info.yaml
  plugins/servicenow-actions/catalog-info.yaml
  plugins/shared-react/catalog-info.yaml
  plugins/sonarqube-actions/catalog-info.yaml
  plugins/tekton-common/catalog-info.yaml
  plugins/tekton/catalog-info.yaml
  plugins/topology-common/catalog-info.yaml
  plugins/topology/catalog-info.yaml
  plugins/web-terminal/catalog-info.yaml
Labels: lgtm

#2098 fix(orchestrator): make "Retrigger" clear to the user
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm

#2095 fix(rbac): add more details to unable to create role alert
  plugins/rbac/README.md
  plugins/rbac/src/components/RolesList/RolesListToolbar.tsx
Labels: lgtm

#2101 chore(release): fix more msr problems
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2050 feat(ocm): add openApi schema and OpenApiRouter
  plugins/ocm-backend/api-docs/.openapi-generator-ignore
  plugins/ocm-backend/api-docs/.openapi-generator/FILES
  plugins/ocm-backend/api-docs/.openapi-generator/VERSION
  plugins/ocm-backend/api-docs/Apis/DefaultApi.md
  plugins/ocm-backend/api-docs/Models/Cluster.md
  plugins/ocm-backend/api-docs/Models/ClusterBase.md
  plugins/ocm-backend/api-docs/Models/ClusterDetails.md
  plugins/ocm-backend/api-docs/Models/ClusterDetails_allocatableResources.md
  plugins/ocm-backend/api-docs/Models/ClusterDetails_availableResources.md
  plugins/ocm-backend/api-docs/Models/ClusterNodesStatus.md
  plugins/ocm-backend/api-docs/Models/ClusterOverview.md
  plugins/ocm-backend/api-docs/Models/ClusterStatus.md
  plugins/ocm-backend/api-docs/Models/ClusterUpdate.md
  plugins/ocm-backend/api-docs/README.md
  plugins/ocm-backend/catalog-info.yaml
  plugins/ocm-backend/dist-dynamic/package.json
  plugins/ocm-backend/dist-dynamic/yarn.lock
  plugins/ocm-backend/openapitools.json
  plugins/ocm-backend/package.json
  plugins/ocm-backend/scripts/openapi-doc.sh
  plugins/ocm-backend/src/schema/openapi.generated.ts
  plugins/ocm-backend/src/schema/openapi.yaml
  plugins/ocm-backend/src/service/router.ts
Labels: lgtm

#2091 feat(licensed-users): add licensed users download link
  plugins/rbac/dev/index.tsx
  plugins/rbac/src/api/LicensedUsersClient.ts
  plugins/rbac/src/components/DownloadUserStatistics.tsx
  plugins/rbac/src/components/RbacPage.test.tsx
  plugins/rbac/src/components/RolesList/RolesList.test.tsx
  plugins/rbac/src/components/RolesList/RolesList.tsx
  plugins/rbac/src/hooks/useCheckIfLicensePluginEnabled.ts
  plugins/rbac/src/plugin.ts
Labels: lgtm

#2100 chore: add deprecation note to feedback and feedback-backend plugins
  plugins/feedback-backend/README.md
  plugins/feedback-backend/package.json
  plugins/feedback/README.md
  plugins/feedback/package.json
Labels: lgtm

#2105 fix(bulk-import): update bulk import exports
  plugins/bulk-import/app-config.janus-idp.yaml
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/BulkImportSidebarItem.tsx
  plugins/bulk-import/src/index.ts
Labels: lgtm

#2106 fix(orchestrator): improve styles of generated field array in the dark theme
  plugins/orchestrator-form-react/src/components/OrchestratorForm.tsx
Labels: lgtm

#2107 fix: add more space for workflow description
  plugins/orchestrator/src/components/WorkflowsTable.tsx
Labels: lgtm

#2110 fix(orchestrator): improve styles of generated field array in the dark theme
  plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
Labels: lgtm

#2109 fix(orchestrator): make "Retrigger" to the user
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm
