Repository janus-idp/backstage-plugins, pull requests merged in 2024-04, with the labels that each got.

#1418 refactor: experimental `embed-as-dependencies` option for the backend
  packages/cli/package.json
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
  packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts
  packages/cli/src/commands/export-dynamic-plugin/command.ts
  packages/cli/src/commands/export-dynamic-plugin/dev.ts
  packages/cli/src/commands/export-dynamic-plugin/frontend.ts
  packages/cli/src/commands/index.ts
  yarn.lock
Labels: approved, lgtm, do-not-merge/hold

#1435 fix(feedback-backend): fix the feedback url for mail and jira
  plugins/feedback-backend/src/mocks/config.ts
  plugins/feedback-backend/src/service/router.ts
Labels: approved, lgtm

#1359 feat(rbac): add conditional access button and sidebar
  plugins/rbac/dev/index.tsx
  plugins/rbac/src/__fixtures__/mockConditionRules.ts
  plugins/rbac/src/api/RBACBackendClient.ts
  plugins/rbac/src/components/ConditionalAccess/ConditionalAccessSidebar.tsx
  plugins/rbac/src/components/ConditionalAccess/types.ts
  plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.test.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/hooks/useConditionRules.test.ts
  plugins/rbac/src/hooks/useConditionRules.ts
Labels: approved, lgtm

#1432 chore: sync yarn.lock
  yarn.lock
Labels: approved, lgtm

#1434 feat(kiali): update dark theme
  plugins/kiali/src/components/BreadcrumbView/BreadcrumbView.tsx
  plugins/kiali/src/components/Charts/SparklineChart.tsx
  plugins/kiali/src/components/Overview/TLSInfo.tsx
  plugins/kiali/src/components/VirtualList/Config.tsx
  plugins/kiali/src/components/VirtualList/Renderers.tsx
  plugins/kiali/src/components/VirtualList/VirtualItem.tsx
  plugins/kiali/src/pages/AppDetails/AppDescription.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/CanaryUpgradeProgress.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/ControlPlaneNamespaceStatus.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/NamespaceLabels.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/OverviewCardControlPlaneNamespace.tsx
  plugins/kiali/src/pages/Overview/OverviewPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadInfo.tsx
  plugins/kiali/src/styles/StyleUtils.ts
Labels: approved, lgtm

#1330 fix(rbac): rework condition policies to bound them to RBAC roles
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/migrations/20240308134410_migrations.js
  plugins/rbac-backend/migrations/20240308134941_migrations.js
  plugins/rbac-backend/src/database/conditional-storage.ts
  plugins/rbac-backend/src/database/conditional.storage.test.ts
  plugins/rbac-backend/src/helper.test.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/condition-validation.ts
  plugins/rbac-backend/src/service/condition.validation.test.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-common/src/types.ts
Labels: lgtm

#1439 fix(orchestrator): update devmode container tag
  plugins/orchestrator-common/src/constants.ts
Labels: approved, lgtm

#1436 fix(orchestrator): only inputs inherited from the assessment workflow should be disabled
  plugins/orchestrator-backend/src/service/DataInputSchemaService.test.ts
  plugins/orchestrator-backend/src/service/DataInputSchemaService.ts
Labels: approved, lgtm

#1449 fix(orchestrator): add lastRunId to overview endpoints
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-common/src/auto-generated/.METADATA.sha1
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator-common/src/types.ts
Labels: approved, lgtm

#1280 feat(rbac): save role modification information to the metadata
  plugins/rbac-backend/migrations/20240404111242_migrations.js
  plugins/rbac-backend/src/database/policy-metadata-storage.test.ts
  plugins/rbac-backend/src/database/role-metadata.test.ts
  plugins/rbac-backend/src/database/role-metadata.ts
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/file-permissions/csv.ts
  plugins/rbac-backend/src/helper.test.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/tsconfig.json
  plugins/rbac-common/src/types.ts
  plugins/rbac/src/components/RoleOverview/AboutCard.test.tsx
  plugins/rbac/src/components/RoleOverview/AboutCard.tsx
Labels: lgtm

#1473 fix(cli): fix entrypoint validation when running with `npx`
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
  packages/cli/src/commands/export-dynamic-plugin/backend-utils.ts
Labels: approved, lgtm

#1478 fix(cli): fix the `embed-as-dependencies` option on the `export-dynamic-plugin` CLI...
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
Labels: approved, lgtm

#1472 feat(feedback): add capture events in feedback plugin
  plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
  plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
  plugins/feedback/src/components/FeedbackTable/FeedbackTable.tsx
  plugins/feedback/src/components/OpcFeedbackComponent/OpcFeedbackComponent.tsx
Labels: approved, lgtm

#1483 chore(deps): tweak READMEs to force semantic release to run for rbac-node and shared-react plugin releases
  plugins/rbac-node/README.md
  plugins/shared-react/README.md
Labels: approved, lgtm

#1482 fix(cli): `node_modules` of the main plugin unexpectedly copied to the `dist-dynamic` folder.
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-dependencies.ts
Labels: lgtm

#1464 chore(deps): migrate from openapi to openapi-ts
  plugins/nexus-repository-manager/package.json
  plugins/nexus-repository-manager/src/hooks/useNexusRepositoryManagerAppData.ts
  plugins/servicenow-actions/dist-dynamic/package.json
  plugins/servicenow-actions/dist-dynamic/yarn.lock
  plugins/servicenow-actions/package.json
  plugins/servicenow-actions/scripts/generate.sh
  plugins/servicenow-actions/src/actions/servicenow/now/table/create-record.ts
  plugins/servicenow-actions/src/actions/servicenow/now/table/delete-record.ts
  plugins/servicenow-actions/src/actions/servicenow/now/table/modify-record.ts
  plugins/servicenow-actions/src/actions/servicenow/now/table/retrieve-record.ts
  plugins/servicenow-actions/src/actions/servicenow/now/table/retrieve-records.ts
  plugins/servicenow-actions/src/actions/servicenow/now/table/update-record.ts
  yarn.lock
Labels: approved, lgtm

#1488 feat(orchestrator): make workflow last run status as link to the workflow last run details page
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionDetailsCard.tsx
  plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
  plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
Labels: approved, lgtm

#1357 feat(bulk-import): allow adding repositories
  plugins/bulk-import/README.md
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesSearchBar.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx
  plugins/bulk-import/src/components/AddRepositories/Illustrations.tsx
  plugins/bulk-import/src/components/AddRepositories/OrganizationColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/OrganizationTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoriesColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/RepositoriesHeader.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/mockData.ts
  plugins/bulk-import/src/components/BulkImportPage.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListToolbar.tsx
  plugins/bulk-import/src/components/Router.test.tsx
  plugins/bulk-import/src/components/Router.tsx
  plugins/bulk-import/src/globals.d.ts
  plugins/bulk-import/src/images/ApprovalTool_Black.svg
  plugins/bulk-import/src/images/ApprovalTool_White.svg
  plugins/bulk-import/src/images/ChooseRepositories_Black.svg
  plugins/bulk-import/src/images/ChooseRepositories_White.svg
  plugins/bulk-import/src/images/EditPullRequest_Black.svg
  plugins/bulk-import/src/images/EditPullRequest_White.svg
  plugins/bulk-import/src/images/GenerateCatalogInfo_Black.svg
  plugins/bulk-import/src/images/GenerateCatalogInfo_White.svg
  plugins/bulk-import/src/images/TrackStatus_Black.svg
  plugins/bulk-import/src/images/TrackStatus_White.svg
  plugins/bulk-import/src/plugin.ts
  plugins/bulk-import/src/routes.ts
  plugins/bulk-import/src/types.ts
  plugins/bulk-import/src/utils/icons.ts
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
Labels: approved, lgtm

#1496 fix(feedback-docs): move out collapsed screenshots
  plugins/feedback/README.md
Labels: approved, lgtm

#1498 fix(notifications): flpath-1163 (#1394)
  plugins/notifications-backend/src/service/handlers.ts
Labels: approved, lgtm

#1503 chore: bump root package.json to 3.2.0 to...
  package.json
Labels: approved, lgtm

#1474 fix(rbac): reduce the number of permissions returned, add isResourced flag
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-common/src/types.ts
Labels: approved, lgtm

#1520 fix(feedback-backend): fix the feedback url for mail and jira
  plugins/feedback-backend/CHANGELOG.md
  plugins/feedback-backend/README.md
  plugins/feedback-backend/src/mocks/config.ts
  plugins/feedback-backend/src/service/router.ts
  plugins/feedback/CHANGELOG.md
  plugins/feedback/README.md
  plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
  plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
  plugins/feedback/src/components/FeedbackTable/FeedbackTable.tsx
  plugins/feedback/src/components/OpcFeedbackComponent/OpcFeedbackComponent.tsx
Labels: approved, lgtm

#1521 docs(orchestrator): fix quick start urls to private repo and make image urls raw
  plugins/orchestrator/README.md
  plugins/orchestrator/docs/quickstart.md
Labels: approved, lgtm

#1430 feat(bulk-import): allow user to select repositories from side panel
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx
  plugins/bulk-import/src/components/AddRepositories/OrganizationTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/ReposSelectDrawerColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/RepositoriesHeader.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/mockData.ts
  plugins/bulk-import/src/types.ts
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
Labels: approved, lgtm

#1513 feat(rbac): lazy load temporary enforcer
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.ts
Labels: approved, lgtm

#1486 feat(rbac): add the optional maxDepth feature
  plugins/rbac-backend/README.md
  plugins/rbac-backend/config.d.ts
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.test.ts
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
  plugins/rbac-backend/src/role-manager/role-manager.test.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: approved, lgtm

#1343 feat(orchestrator): add endpoint to retrigger workflow in error state
  plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/v1.test.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-backend/src/types/apiResponse.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
Labels: approved, lgtm

#1544 fix(orchestrator): fixes v2/instances endpoint (#1414)
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
  plugins/orchestrator-backend/src/service/api/test-utils.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-common/src/models.ts
  plugins/orchestrator/src/__fixtures__/fakeLongProcessInstanceList.ts
  plugins/orchestrator/src/__fixtures__/fakeProcessInstance.ts
Labels: approved, lgtm

#1491 fix(kiali): update load for overview page
  plugins/kiali/src/components/VirtualList/VirtualList.tsx
  plugins/kiali/src/pages/AppList/AppListPage.tsx
  plugins/kiali/src/pages/IstioConfigList/IstioConfigListPage.tsx
  plugins/kiali/src/pages/Overview/ListView/ListViewPage.tsx
  plugins/kiali/src/pages/Overview/OverviewPage.tsx
  plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
  plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
Labels: approved, lgtm

#1551 Update OWNERS - add BethGriggs
  OWNERS
Labels: lgtm

#1549 chore(deps): try another approach to update...
  .github/actions/test/action.yaml
  .github/renovate.json
Labels: lgtm

#1571 chore(renovate): fix warnings, use matchDepPatterns instead
  .github/renovate.json
Labels: approved, lgtm

#1582 fix(feedback): add support for jira cloud instance
  plugins/feedback-backend/README.md
  plugins/feedback-backend/app-config.janus-idp.yaml
  plugins/feedback-backend/config.d.ts
  plugins/feedback-backend/dist-dynamic/package.json
  plugins/feedback-backend/dist-dynamic/yarn.lock
  plugins/feedback-backend/package.json
  plugins/feedback-backend/src/api/index.ts
  plugins/feedback-backend/src/api/jiraApiService.test.ts
  plugins/feedback-backend/src/api/jiraApiService.ts
  plugins/feedback-backend/src/service/router.ts
  plugins/feedback/app-config.janus-idp.yaml
  plugins/feedback/package.json
  plugins/feedback/src/index.ts
Labels: approved, lgtm

#1592 fix(cli): remove the requirement for `app-config` when exporting fronted plugins to dynamic.
  packages/cli/src/lib/bundler/bundlePlugin.ts
  packages/cli/src/lib/bundler/scalprumConfig.ts
  packages/cli/src/lib/bundler/types.ts
Labels: lgtm

#1593 fix(cli): allow exporting dynamic plugins from `frontend-plugin-module` packages.
  packages/cli/src/commands/export-dynamic-plugin/command.ts
Labels: approved, lgtm
