Repository janus-idp/backstage-plugins, pull requests merged in 2024-09, with the labels that each got.

#2111 fix(orchestrator): change api doc generator to markdown
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/docs/index.adoc/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator-ignore
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator/VERSION
  plugins/orchestrator-common/src/generated/docs/markdown/Apis/DefaultApi.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/AssessedProcessInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ErrorResponse.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ExecuteWorkflowRequestDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ExecuteWorkflowResponseDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/FilterInfo.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/FilterValue.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/GetInstancesRequestParams.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/GetOverviewsRequestParams.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/NodeInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/Operator.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/PaginationInfoDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceErrorDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceStatusDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowCategoryDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowDataDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowFormatDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowOverviewDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowOverviewListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowProgressDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowRunStatusDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowSuggestionDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/README.md
  plugins/orchestrator/README.md
Labels: lgtm

#2021 feat(orchestrator): use v2 endpoints to execute workflows
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ExecuteWorkflowResponseDTO.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
Labels: lgtm, ok-to-test

#2030 feat(orchestrator): use v2 endpoint for abortWorkflow
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
Labels: lgtm

#2119 feat(orchestrator): backport use v2 endpoints
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/index.adoc/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator-ignore
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/markdown/.openapi-generator/VERSION
  plugins/orchestrator-common/src/generated/docs/markdown/Apis/DefaultApi.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/AssessedProcessInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ErrorResponse.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ExecuteWorkflowRequestDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ExecuteWorkflowResponseDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/FilterInfo.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/FilterValue.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/GetInstancesRequestParams.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/GetOverviewsRequestParams.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/NodeInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/Operator.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/PaginationInfoDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceErrorDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceStatusDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowCategoryDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowDataDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowFormatDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowOverviewDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowOverviewListResultDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowProgressDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowRunStatusDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/Models/WorkflowSuggestionDTO.md
  plugins/orchestrator-common/src/generated/docs/markdown/README.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator/README.md
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
Labels: lgtm

#2120 fix(shared-react): include css files in shared react folder
  plugins/shared-react/package.json
Labels: lgtm

#2039 fix(rbac): clean up policies when policies files are detached
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/file-permissions/file-watcher.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.ts
  plugins/rbac-backend/src/service/permission-policy.ts
Labels: lgtm

#2049 chore(ci): remove workflows for build/push of janus website
  .github/workflows/pr-website.yaml
  .github/workflows/push-website.yaml
Labels: lgtm

#2031 feat(orchestrator): use v2 endpoint fot getWorkflowSource
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.test.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx
Labels: lgtm

#2121 fix(bulk-import): fix inconsistency with the support levels declared by the plugins
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
  plugins/bulk-import-common/package.json
Labels: lgtm

#2126 chore(release): revert downgrade of cli and orchestrator form react
  packages/cli/package.json
  plugins/orchestrator-form-react/package.json
  yarn.lock
Labels: lgtm

#1816 fix(kiali): assets missing in dist
  plugins/bulk-import-backend/package.json
  plugins/kiali/dev/index.tsx
  plugins/kiali/src/components/Logos/Logos.tsx
  plugins/kiali/src/components/MTls/MTLSIcon.tsx
  yarn.lock
Labels: lgtm

#2129 feat(bulk-import): introduce api catalog info
  plugins/bulk-import-backend/catalog-info.yaml
Labels: lgtm

#2127 feat(orchestrator): add open api documentation
  plugins/orchestrator-backend/src/OrchestratorPlugin.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/docs/html/index.html
Labels: lgtm

#2133 chore(deps): move audit log dep to peerDependencies
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/dist-dynamic/yarn.lock
  plugins/bulk-import-backend/package.json
  plugins/bulk-import/package.json
  plugins/orchestrator-form-react/package.json
  yarn.lock
Labels: lgtm

#2096 fix(rbac): remove tab from rbac page
  plugins/rbac/app-config.janus-idp.yaml
  plugins/rbac/src/components/Administration.test.tsx
  plugins/rbac/src/components/Administration.tsx
  plugins/rbac/src/components/RbacPage.test.tsx
  plugins/rbac/src/components/RbacPage.tsx
  plugins/rbac/src/index.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: lgtm

#2138 chore(release): revert downgrade of bulk import common
  plugins/bulk-import-common/package.json
Labels: lgtm

#2130 fix(orchestrator): typos in auditLog messages
  plugins/orchestrator-backend/src/service/router.ts
Labels: lgtm

#2142 feat(orchestrator): add open api documentation
  plugins/orchestrator-backend/src/OrchestratorPlugin.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/generated/docs/index.html
Labels: lgtm

#2141 fix(orchestrator): fix wrong v2 abort endpoint
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/html/.openapi-generator-ignore
  plugins/orchestrator-common/src/generated/docs/html/.openapi-generator/FILES
  plugins/orchestrator-common/src/generated/docs/html/.openapi-generator/VERSION
  plugins/orchestrator-common/src/generated/docs/html/index.html
  plugins/orchestrator-common/src/generated/docs/markdown/Apis/DefaultApi.md
  plugins/orchestrator-common/src/generated/docs/markdown/README.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator/src/api/OrchestratorClient.test.ts
Labels: lgtm

#2122 fix(rbac): support RejectUnauthorized ssl option for postgres
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
  plugins/rbac-backend/src/database/casbin-adapter-factory.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: lgtm

#2136 fix(rbac): update scaffolder permissions documentation
  plugins/rbac-backend/docs/permissions.md
Labels: lgtm

#2148 chore(release): revert downgrade of bulk-import-backend plugin
  plugins/bulk-import-backend/CHANGELOG.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2150 fix(tekton): fix incorrect image path for signed badge svg
  plugins/tekton/src/components/Icons/SignedBadgeIcon.tsx
  plugins/tekton/src/components/PipelineRunList/PipelineRunRow.tsx
  plugins/tekton/src/imgs/signed-badge.svg
  plugins/tekton/src/utils/image-utils.ts
Labels: lgtm

#2146 fix(bulk-import): make sure import branch is up-to-date to prevent potential conflicts or unchanged files in GH [RHIDP-3901]
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
Labels: lgtm

#2155 chore(release): revert downgrade of audit log
  plugins/audit-log-node/package.json
Labels: lgtm

#2125 fix(quay): fix the security scan sorting in quay plugin
  plugins/quay/dev/__data__/security_vulnerabilities.ts
  plugins/quay/dev/__data__/tags.ts
  plugins/quay/dev/index.tsx
  plugins/quay/src/components/QuayRepository/tableHeading.tsx
  plugins/quay/src/lib/utils.test.ts
  plugins/quay/src/lib/utils.ts
  plugins/quay/src/types.ts
  plugins/quay/tests/quay.spec.ts
Labels: lgtm

#2158 chore(release): revert downgrade of bulk-import-common
  plugins/bulk-import-common/package.json
Labels: approved, lgtm

#2137 fix(bulk-import): backend improvements [RHIDP-3864][RHIDP-3865]
  plugins/bulk-import-backend/dev/index.ts
  plugins/bulk-import-backend/src/dynamic/index.ts
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.test.ts
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
  plugins/bulk-import-backend/src/helpers/pagination.ts
  plugins/bulk-import-backend/src/plugin.ts
  plugins/bulk-import-backend/src/service/githubApiService.test.ts
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/handlers/organizations.ts
  plugins/bulk-import-backend/src/service/handlers/repositories.ts
  plugins/bulk-import-backend/src/service/router.test.ts
  plugins/bulk-import-backend/src/service/router.ts
  yarn.lock
Labels: lgtm

#2117 docs(rbac): add group hierarchy support information
  plugins/rbac-backend/README.md
  plugins/rbac-backend/docs/group-hierarchy.md
  plugins/rbac-backend/docs/images/group-hierarchy-1.svg
  plugins/rbac-backend/docs/images/group-hierarchy-2.svg
  plugins/rbac-backend/docs/images/group-hierarchy-3.svg
  plugins/rbac-backend/docs/images/group-hierarchy-4.svg
Labels: lgtm

#2156 fix(bulk-import): bulk import fixes
  plugins/bulk-import/README.md
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx
  plugins/bulk-import/src/components/BulkImportPage.tsx
  plugins/bulk-import/src/components/PreviewFile/KeyValueTextField.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebar.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebarDrawerContent.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequestForm.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.test.tsx
  plugins/bulk-import/src/components/Repositories/CatalogInfoAction.tsx
  plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListToolbar.tsx
  plugins/bulk-import/src/hooks/useAddedRepositories.ts
  plugins/bulk-import/src/hooks/useRepositories.ts
  plugins/bulk-import/src/types/types.ts
  plugins/bulk-import/src/utils/repository-utils.test.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
Labels: lgtm

#2164 chore(release): revert downgrade of several plugins
  plugins/bulk-import-backend/CHANGELOG.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2160 fix(lightspeed): use lightspeed icon image as bot avatar image
  plugins/lightspeed/src/components/LightspeedChatBox.tsx
Labels: lgtm

#2140 feat(bulk-import): implement server-side search [RHIDP-3884]
  plugins/bulk-import-backend/api-docs/Apis/ImportApi.md
  plugins/bulk-import-backend/api-docs/Apis/OrganizationApi.md
  plugins/bulk-import-backend/api-docs/Apis/RepositoryApi.md
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
  plugins/bulk-import-backend/src/openapi.d.ts
  plugins/bulk-import-backend/src/openapidocument.ts
  plugins/bulk-import-backend/src/schema/openapi.yaml
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/handlers/organizations.ts
  plugins/bulk-import-backend/src/service/handlers/repositories.ts
  plugins/bulk-import-backend/src/service/router.test.ts
  plugins/bulk-import-backend/src/service/router.ts
Labels: lgtm

#2167 chore(release): revert downgrade of bulk import backend
  plugins/bulk-import-backend/CHANGELOG.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2162 chore(deps): fix CVE-2024-45590, CVE-2024-43799, CVE-2024-45296
  plugins/bulk-import-backend/dist-dynamic/yarn.lock
  plugins/feedback-backend/dist-dynamic/yarn.lock
  plugins/kiali-backend/dist-dynamic/yarn.lock
  plugins/ocm-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
  yarn.lock
Labels: kind/security, lgtm

#2168 chore(release): revert downgrade of 'orchestrator-form-api' package
  plugins/orchestrator-form-api/package.json
Labels: lgtm

#2163 fix(bulk-import): refresh the Location entity when the Import is `ADDED`
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/handlers/importStatus.ts
  plugins/bulk-import-backend/src/service/router.test.ts
Labels: lgtm

#2172 chore(release): revert downgrade of orchestrator form api
  plugins/orchestrator-form-api/package.json
Labels: lgtm

#2165 fix(ui): fixed bulk import footer background color in dark theme
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebarDrawerContent.tsx
  yarn.lock
Labels: approved, lgtm

#2176 fix(topology): adding vmi in readme
  plugins/topology/README.md
Labels: lgtm

#2170 docs(rbac): add more clarification around requirements for old and new backend
  plugins/rbac-backend/README.md
Labels: lgtm

#2173 fix(bulk-import): pass search string as query params in the bulk imort apis
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/src/api/BulkImportBackendClient.test.ts
  plugins/bulk-import/src/api/BulkImportBackendClient.ts
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.test.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx
  plugins/bulk-import/src/components/BulkImportPage.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFileSidebar.tsx
  plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListToolbar.tsx
  plugins/bulk-import/src/hooks/useAddedRepositories.test.ts
  plugins/bulk-import/src/hooks/useAddedRepositories.ts
  plugins/bulk-import/src/hooks/useRepositories.test.ts
  plugins/bulk-import/src/hooks/useRepositories.ts
  plugins/bulk-import/src/mocks/mockData.ts
  plugins/bulk-import/src/types/types.ts
  plugins/bulk-import/src/utils/repository-utils.test.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
Labels: lgtm

#2174 fix(orchestrator): remove retrigger
  plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/v1.test.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/QueryParams.ts
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm

#2177 docs(topology): adding vm vmi in clusterrole file for read access
  plugins/topology/manifests/clusterrole.yaml
Labels: lgtm

#2178 fix(bulk-import): handle Location entities created from other sources like the GH discovery as Import candidates [RHIDP-4021]
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/router.test.ts
Labels: lgtm

#2182 chore(release): revert downgrade of `catalog-backend-module-scaffolder-relation-processor`
  plugins/catalog-backend-module-scaffolder-relation-processor/CHANGELOG.md
  plugins/catalog-backend-module-scaffolder-relation-processor/dist-dynamic/package.json
  plugins/catalog-backend-module-scaffolder-relation-processor/package.json
Labels: lgtm

#2175 fix(orchestrator): remove retrigger
  plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/v1.test.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/QueryParams.ts
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: lgtm

#2184 fix(rbac): improve members dropdown to handle large no. of users/groups
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
Labels: lgtm

#2188 chore(release): revert unexpected downgrade of `backstage-plugin-audit-log-node`
  plugins/audit-log-node/package.json
Labels: lgtm

#1977 fix(deps): replace deprecated functionality
  plugins/audit-log-node/README.md
  plugins/kiali-backend/package.json
  plugins/kiali-backend/src/service/router.test.ts
  plugins/kiali-backend/src/service/router.ts
  plugins/matomo-backend/package.json
  plugins/matomo-backend/src/plugin.ts
  plugins/matomo-backend/src/run.ts
  plugins/matomo-backend/src/service/router.ts
  plugins/matomo-backend/src/service/standaloneServer.ts
  plugins/ocm-backend/package.json
  plugins/ocm-backend/src/service/router.ts
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/routerWrapper/index.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/run.ts
  plugins/rbac-backend/src/service/router.test.ts
  plugins/rbac-backend/src/service/router.ts
  plugins/rbac-backend/src/service/standaloneServer.ts
Labels: approved, lgtm

#2194 chore(owners): update approvers
  OWNERS
Labels: lgtm

#2081 feat: update keycloak-admin-client to use v24.0.5
  plugins/keycloak-backend/README.md
  plugins/keycloak-backend/__fixtures__/data.ts
  plugins/keycloak-backend/__fixtures__/helpers.ts
  plugins/keycloak-backend/dev/index.ts
  plugins/keycloak-backend/dev/types.ts
  plugins/keycloak-backend/dist-dynamic/package.json
  plugins/keycloak-backend/dist-dynamic/yarn.lock
  plugins/keycloak-backend/package.json
  plugins/keycloak-backend/src/lib/config.test.ts
  plugins/keycloak-backend/src/lib/read.test.ts
  plugins/keycloak-backend/src/lib/read.ts
  plugins/keycloak-backend/src/lib/types.ts
  plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.test.ts
  plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts
  plugins/keycloak-backend/src/providers/__snapshots__/KeycloakOrgEntityProvider.test.ts.snap
  plugins/keycloak-backend/src/run.ts
  yarn.lock
Labels: lgtm

#2198 chore(release): catch topology 1.3.x up with showcase 1.3.x
  plugins/topology/CHANGELOG.md
  plugins/topology/README.md
  plugins/topology/manifests/clusterrole.yaml
  plugins/topology/package.json
  plugins/topology/src/common/components/Status.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyVirtualMachineDetails.tsx
  plugins/topology/src/utils/selector.ts
  plugins/topology/src/utils/vm-status-utils.ts
  plugins/topology/src/vm-const.ts
Labels: approved, lgtm

#2201 chore(release): catch rbac 1.3.x up with showcase 1.3.x
  plugins/audit-log-node/README.md
  plugins/audit-log-node/package.json
  plugins/rbac-backend/CHANGELOG.md
  plugins/rbac-backend/README.md
  plugins/rbac-backend/docs/group-hierarchy.md
  plugins/rbac-backend/docs/images/group-hierarchy-1.svg
  plugins/rbac-backend/docs/images/group-hierarchy-2.svg
  plugins/rbac-backend/docs/images/group-hierarchy-3.svg
  plugins/rbac-backend/docs/images/group-hierarchy-4.svg
  plugins/rbac-backend/docs/permissions.md
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
  plugins/rbac-backend/src/database/casbin-adapter-factory.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/file-permissions/file-watcher.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/yaml-conditional-file-watcher.ts
  plugins/rbac-backend/src/run.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-backend/src/service/router.test.ts
  plugins/rbac-backend/src/service/router.ts
  plugins/rbac-backend/src/service/standaloneServer.ts
  plugins/rbac/CHANGELOG.md
  plugins/rbac/app-config.janus-idp.yaml
  plugins/rbac/package.json
  plugins/rbac/src/components/Administration.test.tsx
  plugins/rbac/src/components/Administration.tsx
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
  plugins/rbac/src/components/RbacPage.test.tsx
  plugins/rbac/src/components/RbacPage.tsx
  plugins/rbac/src/components/RolesList/DeleteDialogContext.tsx
  plugins/rbac/src/components/RolesList/DeleteRole.test.tsx
  plugins/rbac/src/components/RolesList/DeleteRole.tsx
  plugins/rbac/src/components/RolesList/RolesList.tsx
  plugins/rbac/src/index.ts
  plugins/rbac/tests/rbac.spec.ts
Labels: approved

#2208 fix(orchestrator): v2 inputSchema API gets stuck for specific workflow
  plugins/orchestrator-backend/src/service/router.ts
Labels: lgtm

#2222 chore(deps): bump all plugins to use cli 1.14.0 in main
  plugins/3scale-backend/package.json
  plugins/argocd/package.json
  plugins/lightspeed/package.json
  plugins/rbac-backend-module-test/package.json
  yarn.lock
Labels: lgtm

#2224 chore(build): regenerate plugin yarn.lock
  plugins/3scale-backend/dist-dynamic/package.json
  plugins/lightspeed-backend/dist-dynamic/package.json
  plugins/rbac-backend-module-test/dist-dynamic/package.json
  plugins/rbac-backend-module-test/dist-dynamic/yarn.lock
Labels: lgtm

#2211 feat(lightspeed): add backend config and /conversations/:conversation_id GET&DELETE API
  plugins/lightspeed-backend/README.md
  plugins/lightspeed-backend/config.d.ts
  plugins/lightspeed-backend/package.json
  plugins/lightspeed-backend/src/handlers/chatHistory.test.ts
  plugins/lightspeed-backend/src/handlers/chatHistory.ts
  plugins/lightspeed-backend/src/service/router.test.ts
  plugins/lightspeed-backend/src/service/router.ts
  plugins/lightspeed-backend/src/service/types.ts
  plugins/lightspeed-backend/src/service/validation.ts
  yarn.lock
Labels: lgtm

#2229 fix(orchestrator): remove field 'variables' from ProcessInstanceDTO
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/html/index.html
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceDTO.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
Labels: lgtm

#2230 fix(lightspeed): generate dist-scalprum as part of npm prepack script
  plugins/lightspeed/package.json
Labels: lgtm

#2231 fix(lightspeed): update the version to 0.1.2
  plugins/lightspeed/package.json
Labels: lgtm

#2169 fix(orchestrator): improve error handling in SonataFlowService fetch
  plugins/orchestrator-backend/src/service/SonataFlowService.test.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
Labels: lgtm

#2233 fix(orchestrator): revert remove field 'variables' from ProcessInsanceDTO (#2229)
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/html/index.html
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceDTO.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
Labels: lgtm

#2219 chore: update incubator-kie-sonataflow-devmode image to latest
  plugins/orchestrator-common/src/constants.ts
Labels: lgtm

#1803 fix(topology): remove usage of pf react icons
  plugins/shared-react/package.json
  plugins/shared-react/src/components/common/Status.tsx
  plugins/shared-react/src/components/index.ts
  plugins/tekton/package.json
  plugins/tekton/src/components/Icons/CriticalRiskIcon.tsx
  plugins/tekton/src/components/Icons/EqualsIcon.tsx
  plugins/tekton/src/components/Icons/LinkToSbomIcon.tsx
  plugins/tekton/src/components/Icons/OutputIcon.tsx
  plugins/tekton/src/components/Icons/SignedBadge.tsx
  plugins/tekton/src/components/Icons/SignedBadgeIcon.tsx
  plugins/tekton/src/components/Icons/ViewLogsIcon.tsx
  plugins/tekton/src/components/PipelineRunList/PipelineRunList.test.tsx
  plugins/tekton/src/components/PipelineRunList/PipelineRunRow.tsx
  plugins/tekton/src/components/PipelineRunList/PipelineRunSBOMLink.tsx
  plugins/tekton/src/components/PipelineRunList/PipelineRunVulnerabilities.tsx
  plugins/tekton/src/components/PipelineRunList/PlrStatus.tsx
  plugins/tekton/src/components/PipelineRunLogs/PipelineRunLogDialog.tsx
  plugins/tekton/src/components/PipelineRunLogs/PodLogsDownloadLink.tsx
  plugins/tekton/src/components/PipelineRunOutput/PipelineRunOutputDialog.tsx
  plugins/tekton/src/components/common/Status.css
  plugins/tekton/src/components/common/Status.tsx
  plugins/tekton/src/components/common/index.ts
  plugins/tekton/src/components/pipeline-topology/PipelineVisualizationStepList.tsx
  plugins/tekton/src/utils/pipeline-topology-utils.ts
  plugins/topology/package.json
  plugins/topology/src/common/components/Status.css
  plugins/topology/src/common/components/Status.tsx
  plugins/topology/src/components/Graph/VMNode.tsx
  plugins/topology/src/components/Graph/decorators/Decorator.css
  plugins/topology/src/components/Graph/decorators/Decorator.tsx
  plugins/topology/src/components/Graph/decorators/EditDecorator.test.tsx
  plugins/topology/src/components/Graph/decorators/EditDecorator.tsx
  plugins/topology/src/components/Graph/decorators/PipelineDecoratorBubble.tsx
  plugins/topology/src/components/Graph/decorators/PipelineRunDecorator.tsx
  plugins/topology/src/components/Graph/decorators/UrlDecorator.tsx
  plugins/topology/src/components/Icons/BitbucketIcon.tsx
  plugins/topology/src/components/Icons/CheIcon.tsx
  plugins/topology/src/components/Icons/GitAltIcon.tsx
  plugins/topology/src/components/Icons/GithubIcon.tsx
  plugins/topology/src/components/Icons/GitlabIcon.tsx
  plugins/topology/src/components/Icons/RouteDecoratorIcon.tsx
  plugins/topology/src/components/Icons/UrlDecoratorIcon.tsx
  plugins/topology/src/components/Icons/VirtualMachineIcon.tsx
  plugins/topology/src/components/Topology/TopologyEmptyState.css
  plugins/topology/src/components/Topology/TopologyEmptyState.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PLRlist.test.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PLRlist.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.test.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyResourcesTabPanel.tsx
  plugins/topology/src/components/Topology/TopologySideBar/TopologyVirtualMachineDetails.tsx
  yarn.lock
Labels: lgtm

#2180 feat(janus-idp/cli): add `package package-dynamic-plugins` command
  packages/cli/src/commands/index.ts
  packages/cli/src/commands/package-dynamic-plugins/command.ts
  packages/cli/src/commands/package-dynamic-plugins/index.ts
Labels: lgtm

#2240 chore(release): revert unexpected downgrade of `backstage-plugin-topology-common`
  plugins/topology-common/package.json
Labels: lgtm

#2143 feat(rbac): allow to disable group inheritance
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
  plugins/rbac-backend/src/role-manager/role-manager.test.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
Labels: lgtm

#2228 fix(rbac): fix ownerRefs alias after upgrade backstage to 1.29
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: lgtm

#2189 feat(aap)!: migrate to the new backend and remove deprecations
  plugins/aap-backend/README.md
  plugins/aap-backend/config.d.ts
  plugins/aap-backend/dev/index.ts
  plugins/aap-backend/dist-dynamic/package.json
  plugins/aap-backend/dist-dynamic/yarn.lock
  plugins/aap-backend/package.json
  plugins/aap-backend/src/alpha.ts
  plugins/aap-backend/src/clients/AapResourceConnector.ts
  plugins/aap-backend/src/dynamic/index.ts
  plugins/aap-backend/src/index.ts
  plugins/aap-backend/src/module.test.ts
  plugins/aap-backend/src/module.ts
  plugins/aap-backend/src/providers/AapResourceEntityProvider.test.ts
  plugins/aap-backend/src/providers/AapResourceEntityProvider.ts
  plugins/aap-backend/src/providers/config.ts
  plugins/aap-backend/src/providers/types.ts
  plugins/aap-backend/src/run.ts
  yarn.lock
Labels: lgtm

#2253 chore(release): revert msr downgrade of bulk import common
  plugins/bulk-import-common/package.json
Labels: lgtm

#2236 feat(keycloak-backend)!: migrate to the new backend and remove deprecations
  plugins/keycloak-backend/README.md
  plugins/keycloak-backend/__fixtures__/helpers.ts
  plugins/keycloak-backend/config.d.ts
  plugins/keycloak-backend/dist-dynamic/package.json
  plugins/keycloak-backend/package.json
  plugins/keycloak-backend/src/alpha.ts
  plugins/keycloak-backend/src/dynamic/index.ts
  plugins/keycloak-backend/src/index.ts
  plugins/keycloak-backend/src/lib/config.test.ts
  plugins/keycloak-backend/src/lib/config.ts
  plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.test.ts
  plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.ts
  plugins/keycloak-backend/src/module/index.ts
  plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.test.ts
  plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts
Labels: lgtm

#2251 fix(ui): updated tabs indicator color
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.tsx
Labels: lgtm

#2256 chore(release): revert downgrade by MSR of bulk import backend
  plugins/bulk-import-backend/CHANGELOG.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2250 chore: update theme package version for plugins
  packages/app/package.json
  plugins/acr/package.json
  plugins/analytics-module-matomo/package.json
  plugins/analytics-provider-segment/package.json
  plugins/argocd/package.json
  plugins/dynamic-plugins-info/package.json
  plugins/jfrog-artifactory/package.json
  plugins/kiali/package.json
  plugins/matomo/package.json
  plugins/nexus-repository-manager/package.json
  plugins/ocm/package.json
  plugins/openshift-image-registry/package.json
  plugins/orchestrator/package.json
  plugins/quay/package.json
  plugins/rbac/package.json
  plugins/tekton/package.json
  plugins/topology/package.json
  plugins/web-terminal/package.json
  yarn.lock
Labels: lgtm

#2238 feat(lightspeed): update /v1/query to use streaming and return chunks in http response
  plugins/lightspeed-backend/src/service/router.test.ts
  plugins/lightspeed-backend/src/service/router.ts
Labels: lgtm

#2259 feat(sonarqube-actions)!: migrate to the new Backend System and remove deprecations
  plugins/sonarqube-actions/README.md
  plugins/sonarqube-actions/dist-dynamic/package.json
  plugins/sonarqube-actions/dist-dynamic/yarn.lock
  plugins/sonarqube-actions/examples/templates/01-sonar-template.yaml
  plugins/sonarqube-actions/package.json
  plugins/sonarqube-actions/src/alpha.ts
  plugins/sonarqube-actions/src/dynamic/index.ts
  plugins/sonarqube-actions/src/index.ts
Labels: lgtm

#2214 feat(quay-actions)!: migrate to the new backend and remove deprecations #1254
  plugins/quay-actions/README.md
  plugins/quay-actions/dist-dynamic/package.json
  plugins/quay-actions/dist-dynamic/yarn.lock
  plugins/quay-actions/package.json
  plugins/quay-actions/src/alpha.ts
  plugins/quay-actions/src/dynamic/index.ts
  plugins/quay-actions/src/index.ts
Labels: lgtm

#2241 feat(regex-actions)!: migrate to the new backend and remove deprecations
  plugins/regex-actions/README.md
  plugins/regex-actions/dist-dynamic/package.json
  plugins/regex-actions/dist-dynamic/yarn.lock
  plugins/regex-actions/examples/templates/01-regex-template.yaml
  plugins/regex-actions/package.json
  plugins/regex-actions/src/alpha.ts
  plugins/regex-actions/src/dynamic/index.ts
  plugins/regex-actions/src/index.ts
Labels: lgtm

#2249 chore: add deprecation note to acr plugin
  plugins/acr/README.md
  plugins/acr/package.json
Labels: lgtm

#2254 chore(deps): bump to dset@^3.1.4
  package.json
  yarn.lock
Labels: lgtm

#2235 fix(orchestrator): remove field 'variables' from ProcessInstanceDTO
  plugins/orchestrator-common/src/generated/.METADATA.sha1
  plugins/orchestrator-common/src/generated/api/definition.ts
  plugins/orchestrator-common/src/generated/client/api.ts
  plugins/orchestrator-common/src/generated/docs/html/index.html
  plugins/orchestrator-common/src/generated/docs/markdown/Models/ProcessInstanceDTO.md
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowRunDetail.ts
Labels: lgtm

#2247 fix(orchestrator): fix ProcessInstanceDTO mapping
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
Labels: lgtm

#2270 chore(release): revert downgrade of bulk import backend by MSR
  plugins/bulk-import-backend/CHANGELOG.md
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/package.json
Labels: lgtm

#2271 chore: remove dynamic-plugins-info
  .github/renovate.json
  catalog-info.yaml
  plugins/dynamic-plugins-info/.eslintrc.js
  plugins/dynamic-plugins-info/.versionhistory.md
  plugins/dynamic-plugins-info/CHANGELOG.md
  plugins/dynamic-plugins-info/CONTRIBUTING.md
  plugins/dynamic-plugins-info/README.md
  plugins/dynamic-plugins-info/app-config.janus-idp.yaml
  plugins/dynamic-plugins-info/catalog-info.yaml
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/images/screenshot-plugin-list.png
  plugins/dynamic-plugins-info/package.json
  plugins/dynamic-plugins-info/src/__fixtures__/listLoadedPluginsResult.ts
  plugins/dynamic-plugins-info/src/api/DynamicPluginsInfoClient.ts
  plugins/dynamic-plugins-info/src/api/types.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsInfoContent/DynamicPluginsInfoContent.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.tsx
  plugins/dynamic-plugins-info/src/index.ts
  plugins/dynamic-plugins-info/src/plugin.test.ts
  plugins/dynamic-plugins-info/src/plugin.ts
  plugins/dynamic-plugins-info/src/routes.ts
  plugins/dynamic-plugins-info/src/setupTests.ts
  plugins/dynamic-plugins-info/tsconfig.json
  plugins/dynamic-plugins-info/turbo.json
Labels: lgtm

#2232 feat(bulk-import)!: migrate to the new Backend System and remove deprecations [RHIDP-4061]
  plugins/bulk-import-backend/README.md
  plugins/bulk-import-backend/__fixtures__/catalog/locations.json
  plugins/bulk-import-backend/__fixtures__/github/app/installations/app-installation-1-access-tokens.json
  plugins/bulk-import-backend/__fixtures__/github/app/installations/app-installation-1.json
  plugins/bulk-import-backend/__fixtures__/github/app/installations/repositories.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/github.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/my-org-1.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/my-org-2.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/octocat.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/repos/my-ent-org--no-repos.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/repos/my-ent-org-1.json
  plugins/bulk-import-backend/__fixtures__/github/orgs/repos/my-ent-org-2.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-ent-org-2/A2/repo.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-org-1/my-repo-with-existing-catalog-info-in-default-branch/contents/catalog-info.yaml.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-org-1/my-repo-with-existing-catalog-info-in-default-branch/repo.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-org-1/my-repo-with-no-catalog-info-in-default-branch-and-import-pr/pulls/open.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-org-1/my-repo-with-no-catalog-info-in-default-branch-and-import-pr/repo.json
  plugins/bulk-import-backend/__fixtures__/github/repos/my-org-1/my-repo-with-no-catalog-info-in-default-branch-and-no-import-pr/repo.json
  plugins/bulk-import-backend/__fixtures__/github/repos/octocat/my-awesome-repo/repo.json
  plugins/bulk-import-backend/__fixtures__/github/user/orgs.json
  plugins/bulk-import-backend/__fixtures__/github/user/repos.json
  plugins/bulk-import-backend/__fixtures__/github/user/user.json
  plugins/bulk-import-backend/__fixtures__/handlers.ts
  plugins/bulk-import-backend/dev/index.ts
  plugins/bulk-import-backend/dev/types.ts
  plugins/bulk-import-backend/dist-dynamic/package.json
  plugins/bulk-import-backend/dist-dynamic/yarn.lock
  plugins/bulk-import-backend/package.json
  plugins/bulk-import-backend/src/alpha.ts
  plugins/bulk-import-backend/src/dynamic/index.ts
  plugins/bulk-import-backend/src/helpers/GithubAppManager.test.ts
  plugins/bulk-import-backend/src/helpers/GithubAppManager.ts
  plugins/bulk-import-backend/src/helpers/auditLogUtils.ts
  plugins/bulk-import-backend/src/helpers/auth.ts
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.test.ts
  plugins/bulk-import-backend/src/helpers/catalogInfoGenerator.ts
  plugins/bulk-import-backend/src/helpers/index.ts
  plugins/bulk-import-backend/src/helpers/loggingUtils.ts
  plugins/bulk-import-backend/src/index.ts
  plugins/bulk-import-backend/src/plugin.test.ts
  plugins/bulk-import-backend/src/plugin.ts
  plugins/bulk-import-backend/src/run.ts
  plugins/bulk-import-backend/src/service/githubApiService.test.ts
  plugins/bulk-import-backend/src/service/githubApiService.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.test.ts
  plugins/bulk-import-backend/src/service/handlers/bulkImports.ts
  plugins/bulk-import-backend/src/service/handlers/importStatus.ts
  plugins/bulk-import-backend/src/service/handlers/organizations.ts
  plugins/bulk-import-backend/src/service/handlers/ping.ts
  plugins/bulk-import-backend/src/service/handlers/repositories.ts
  plugins/bulk-import-backend/src/service/router.test.ts
  plugins/bulk-import-backend/src/service/router.ts
  plugins/bulk-import-backend/src/types.ts
  yarn.lock
Labels: lgtm

#2261 chore(keycloak-backend): display cause of error while logging error
  plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts
Labels: lgtm
