Repository janus-idp/backstage-plugins, pull requests merged in 2024-02, with the labels that each got.

#1158 chore(dynamic-plugins-info): export config
  plugins/dynamic-plugins-info/package.json
Labels: approved, lgtm

#1161 fix: add missing alpha dynamic plugin entry points
  plugins/ocm-backend/src/alpha.ts
  plugins/orchestrator-backend/src/alpha.ts
Labels: approved, lgtm

#1148 docs(tekton): add tekton plugin documentation to enable UI elements
  plugins/tekton/README.md
  plugins/tekton/images/tekton-plugin-acs-output.png
  plugins/tekton/images/tekton-plugin-ec-output.png
  plugins/tekton/images/tekton-plugin-pipelinerun-output.png
  plugins/tekton/images/tekton-plugin-vulnerabilities.png
Labels: approved, lgtm

#1152 fix(tekton): external sbom view action should not open logs modal
  plugins/tekton/src/__fixtures__/1-pipelinesData.ts
  plugins/tekton/src/__fixtures__/taskRunData.ts
  plugins/tekton/src/components/PipelineRunList/PipelineRunRowActions.tsx
  plugins/tekton/src/components/PipelineRunList/__tests__/PipelineRunRowActions.test.tsx
  plugins/tekton/src/hooks/useAllWatchResources.test.ts
  plugins/tekton/src/utils/taskRun-utils.test.ts
Labels: approved, lgtm

#1157 feat(topology): added default runtime icon to topology nodes
  plugins/topology/src/data-transforms/data-transformer.ts
  plugins/topology/src/imgs/logos/defaulthub.svg
  plugins/topology/src/utils/icons.ts
Labels: approved, lgtm

#1155 fix(rbac): update the RBAC frontend plugin readme
  plugins/rbac/README.md
Labels: approved, lgtm

#1163 fix(rbac): set up higher jest timeout for rbac db tests
  plugins/rbac-backend/src/database/policy-metadata-storage.test.ts
  plugins/rbac-backend/src/database/role-metadata.test.ts
Labels: approved, lgtm

#1166 fix(3scale): modify 3scale environment variables
  plugins/3scale-backend/app-config.janus-idp.yaml
Labels: approved, lgtm

#1170 fix(cli): embedded alpha module dependencies not hoisted.
  packages/cli/src/commands/export-dynamic-plugin/backend.ts
  packages/cli/src/lib/builder/embedPlugin.ts
Labels: approved, lgtm

#1173 fix(3scale): modify 3scale environment variables - using THREESCALE
  plugins/3scale-backend/app-config.janus-idp.yaml
Labels: approved, lgtm

#1144 chore(orchestrator): add new code owner
  plugins/orchestrator-backend/OWNERS
  plugins/orchestrator-common/OWNERS
  plugins/orchestrator/OWNERS
Labels: approved, lgtm

#1122 fix(topology/tekton): stop polling after log streaming completes
  plugins/tekton/README.md
  plugins/tekton/src/hooks/usePodLogsOfPipelineRun.ts
  plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.test.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogs.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.test.tsx
  plugins/topology/src/components/Topology/TopologySideBar/PodLogs/PodLogsDialog.tsx
  plugins/topology/src/hooks/usePodLogs.test.ts
  plugins/topology/src/hooks/usePodLogs.ts
Labels: approved, lgtm

#1181 fix(orchestrator): removes the divider from the workflow definition card
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
Labels: approved, lgtm

#1180 feat(kiali): add KialiPage Component
  plugins/kiali/DEVELOPMENT.md
  plugins/kiali/README.md
  plugins/kiali/app-config.janus-idp.yaml
  plugins/kiali/dev/index.tsx
  plugins/kiali/package.json
  plugins/kiali/src/Router.tsx
  plugins/kiali/src/components/About/AboutUIModal.tsx
  plugins/kiali/src/components/DebugInformation/DebugInformation.tsx
  plugins/kiali/src/components/MessageCenter/MessageCenter.tsx
  plugins/kiali/src/index.ts
  plugins/kiali/src/pages/Kiali/Header/Header.tsx
  plugins/kiali/src/pages/Kiali/Header/HelpKiali.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiHeaderEntity.tsx
  plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx
  plugins/kiali/src/pages/Kiali/KialiEntity.tsx
  plugins/kiali/src/pages/Kiali/KialiPage.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/OverviewCard.tsx
  plugins/kiali/src/pages/Overview/OverviewPage.tsx
  plugins/kiali/src/plugin.ts
  plugins/kiali/src/store/KialiProvider.tsx
  plugins/kiali/src/utils/entityFilter.ts
Labels: approved, lgtm

#1179 feat: add support for the new backend system to the `rbac-backend` plugin
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/index.ts
  plugins/rbac-backend/src/plugin.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-node/.eslintrc.js
  plugins/rbac-node/README.md
  plugins/rbac-node/package.json
  plugins/rbac-node/src/extensions.ts
  plugins/rbac-node/src/index.ts
  plugins/rbac-node/src/setupTests.ts
  plugins/rbac-node/src/types/index.ts
  plugins/rbac-node/src/types/types.ts
  plugins/rbac-node/tsconfig.json
  plugins/rbac-node/turbo.json
Labels: approved, lgtm

#1185 feat(rbac): use relative links
  plugins/rbac/src/components/CreateRole/CreateRolePage.tsx
  plugins/rbac/src/components/CreateRole/EditRolePage.tsx
  plugins/rbac/src/components/CreateRole/RoleForm.tsx
  plugins/rbac/src/components/EditRole.tsx
  plugins/rbac/src/components/RbacPage.tsx
  plugins/rbac/src/components/RoleOverview/MembersCard.tsx
  plugins/rbac/src/components/RoleOverview/PermissionsCard.tsx
  plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
  plugins/rbac/src/components/Router.tsx
Labels: approved, lgtm

#1187 fix(rbac): show 0 if no members in a group
  plugins/rbac/src/components/CreateRole/AddedMembersTableColumn.tsx
  plugins/rbac/src/utils/create-role-utils.ts
Labels: approved, lgtm

#1186 fix(kiali): namespaceSelector is removing options
  plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx
Labels: approved, lgtm

#1189 fix(rbac): add test for 0 members in group
  plugins/rbac/src/utils/create-role-utils.test.ts
Labels: approved, lgtm

#1191 fix(orchestrator): resolve inconsistency with workflow run average duration format
  plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.test.ts
  plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
Labels: approved, lgtm

#1176 feat: build Information dialog component to show confirmation or alert
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/InfoDialog.stories.tsx
  plugins/orchestrator/src/components/InfoDialog.tsx
Labels: approved, lgtm

#1129 feat(kiali): workloads page list
  plugins/kiali/dev/__fixtures__/index.ts
  plugins/kiali/dev/__fixtures__/namespaces/bookinfo/workloads.json
  plugins/kiali/dev/__fixtures__/namespaces/istio-system/workloads.json
  plugins/kiali/dev/__fixtures__/namespaces/travel-agency/workloads.json
  plugins/kiali/dev/__fixtures__/namespaces/travel-control/workloads.json
  plugins/kiali/dev/__fixtures__/namespaces/travel-portal/workloads.json
  plugins/kiali/dev/index.tsx
  plugins/kiali/src/Router.tsx
  plugins/kiali/src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  plugins/kiali/src/components/FilterList/FilterHelper.ts
  plugins/kiali/src/components/Filters/StatefulFilters.tsx
  plugins/kiali/src/components/Health/HealthDetails.tsx
  plugins/kiali/src/components/Health/HealthIndicator.tsx
  plugins/kiali/src/components/Label/Label.tsx
  plugins/kiali/src/components/Link/IstioObjectLink.ts
  plugins/kiali/src/components/Time/TimeDurationComponent.tsx
  plugins/kiali/src/components/VirtualList/Config.tsx
  plugins/kiali/src/components/VirtualList/Renderers.tsx
  plugins/kiali/src/components/VirtualList/VirtualItem.tsx
  plugins/kiali/src/components/VirtualList/VirtualList.tsx
  plugins/kiali/src/helpers/LabelFilterHelper.ts
  plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiTabs.tsx
  plugins/kiali/src/pages/Kiali/KialiPage.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/OverviewCard.tsx
  plugins/kiali/src/pages/Overview/OverviewPage.tsx
  plugins/kiali/src/pages/Overview/OverviewToolbar.tsx
  plugins/kiali/src/pages/WorkloadList/FiltersAndSorts.tsx
  plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
  plugins/kiali/src/plugin.ts
  plugins/kiali/src/routes.ts
  plugins/kiali/src/services/Api.ts
  plugins/kiali/src/types/AppList.ts
  plugins/kiali/src/types/NamespaceInfo.tsx
  plugins/kiali/src/types/ServiceList.ts
  plugins/kiali/src/utils/SafeRender.tsx
Labels: approved, lgtm

#1194 fix(topology): fix to layout nodes correctly on first load
  plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.test.tsx
  plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx
  plugins/topology/src/components/Topology/TopologyWorkloadView.test.tsx
  yarn.lock
Labels: approved, lgtm

#1171 fix(rbac): csv updates no longer require server restarts
  plugins/rbac-backend/README.md
  plugins/rbac-backend/config.d.ts
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policies-actions.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/duplicate-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/entityref-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/permission-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/invalid-csv/role-entityref-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/valid-csv/rbac-policy.csv
  plugins/rbac-backend/src/__fixtures__/data/valid-csv/updated-rbac-policy.csv
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/file-permissions/csv.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-validation.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-backend/src/service/test/data/rbac-policy.csv
Labels: approved, lgtm

#1192 chore(dynamic-plugins-info): update readme
  plugins/dynamic-plugins-info/README.md
  plugins/dynamic-plugins-info/images/screenshot-plugin-list.png
Labels: approved, lgtm

#1199 fix(orchestrator): filter out `null` values from action input
  plugins/orchestrator-backend/src/service/router.ts
Labels: approved, lgtm

#1196 fix(orchestrator): the instance details card content is cropped
  plugins/orchestrator/src/__fixtures__/fakeWorkflowRunDetails.ts
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.stories.tsx
  plugins/orchestrator/src/components/WorkflowRunDetails.tsx
Labels: approved, lgtm

#1202 fix(kiali): add corner cases, fix some issues and improve dev env
  plugins/kiali/README.md
  plugins/kiali/RHDH.md
  plugins/kiali/dev/__fixtures__/general/statusError.json
  plugins/kiali/dev/index.tsx
  plugins/kiali/dev/mockEntity.ts
  plugins/kiali/images/janus/catalog-list.png
  plugins/kiali/images/janus/entity.png
  plugins/kiali/images/janus/overview_tab.png
  plugins/kiali/images/logo/kiali_logo_lightbkg_1280px.png
  plugins/kiali/images/logo/kiali_logo_lightbkg_200px.png
  plugins/kiali/images/logo/kiali_logo_lightbkg_600px.png
  plugins/kiali/images/rhdh/RHDH_kiali_page_overview.png
  plugins/kiali/images/rhdh/RHDH_kiali_page_workloads.png
  plugins/kiali/src/Router.tsx
  plugins/kiali/src/pages/Kiali/KialiNoAnnotation.tsx
  plugins/kiali/src/pages/Kiali/KialiNoResources.tsx
  plugins/kiali/src/store/KialiProvider.tsx
Labels: approved, lgtm

#1208 fix(rbac): allow for super users to have allow all access
  plugins/rbac-backend/README.md
  plugins/rbac-backend/config.d.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
Labels: approved, lgtm

#1209 chore: update the contributing guide with plugin provider responsibilities
  CONTRIBUTING.md
Labels: approved, lgtm

#1123 feat(orchestrator): add OpenAPI support
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/index.ts
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator-common/src/openapi/types.ts
Labels: approved, lgtm

#1213 fix(rbac): fix rbac tab route
  packages/backend/package.json
  plugins/rbac/src/components/RbacPage.tsx
Labels: approved, lgtm

#1212 fix(tekton): upgrade to use latest @aonic-ui/pipelines package
  plugins/tekton/package.json
  plugins/tekton/src/__fixtures__/1-pipelinesData.ts
  plugins/tekton/src/components/PipelineRunList/PipelineRunOutput.tsx
  plugins/tekton/src/components/PipelineRunList/__tests__/PipelineRunOutput.test.tsx
  plugins/tekton/src/hooks/usePipelineRunOutputData.ts
  plugins/tekton/src/hooks/usePipelineRunScanResults.test.ts
  plugins/tekton/src/types/output.ts
  plugins/tekton/src/types/taskRun.ts
  plugins/tekton/src/utils/taskRun-utils.test.ts
  plugins/tekton/src/utils/taskRun-utils.ts
  yarn.lock
Labels: approved, lgtm

#1218 chore(tekton,quay): add OWNERS file to tekton and quay plugins
  plugins/quay/OWNERS
  plugins/tekton/OWNERS
Labels: approved, lgtm

#1217 fix(orchestrator): resolve mismatch between execution data and composed schema
  plugins/orchestrator-backend/__fixtures__/mockComposedGreetingWorfklow.ts
  plugins/orchestrator-backend/__fixtures__/mockGreetingWorkflowData.ts
  plugins/orchestrator-backend/__fixtures__/mockSpringBootWorkflowData.ts
  plugins/orchestrator-backend/src/service/DataInputSchemaService.test.ts
  plugins/orchestrator-backend/src/service/DataInputSchemaService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/types.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaDifferentTypes.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStep.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowDataInputSchemaResponseMultiStepInitialState.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowInputSchemaResponse.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.stories.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/ExecuteWorkflowPage.tsx
  plugins/orchestrator/src/components/ExecuteWorkflowPage/StepperForm.tsx
Labels: approved, lgtm

#1201 test(quay): add first playwright tests
  .github/workflows/pr-playwright.yaml
  .gitignore
  CONTRIBUTING.md
  plugins/quay/dev/index.tsx
  plugins/quay/package.json
  plugins/quay/playwright.config.ts
  plugins/quay/tests/quay.spec.ts
  yarn.lock
Labels: approved, lgtm

#1215 feat(orchestrator): display a confirmation dialog before the user aborts a running workflow
  plugins/orchestrator/src/components/InfoDialog.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: approved, lgtm

#1222 chore(dynamic-plugins-info): add test
  plugins/dynamic-plugins-info/dev/index.tsx
  plugins/dynamic-plugins-info/src/__fixtures__/listLoadedPluginsResult.ts
  plugins/dynamic-plugins-info/src/components/DynamicPluginsTable/DynamicPluginsTable.test.tsx
Labels: approved, lgtm

#1207 fix(kiali): update styles, remove item details links
  plugins/kiali/src/components/VirtualList/Renderers.tsx
  plugins/kiali/src/components/VirtualList/VirtualList.tsx
  plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
  plugins/kiali/src/styles/StyleUtils.ts
Labels: approved, lgtm

#1224 fix(rbac): add data-testid, names and aria-label to RBAC UI components
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
  plugins/rbac/src/components/CreateRole/MembersDropdownOption.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/components/CreateRole/PoliciesCheckboxGroup.tsx
  plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx
  plugins/rbac/src/components/RolesList/RolesList.test.tsx
  plugins/rbac/src/components/RolesList/RolesListColumns.tsx
  plugins/rbac/src/components/SnackbarAlert.tsx
Labels: approved, lgtm

#1214 fix(rbac): drop database disabled mode
  plugins/rbac-backend/README.md
  plugins/rbac-backend/config.d.ts
  plugins/rbac-backend/migrations/20240215154456_migrations.js
  plugins/rbac-backend/model/rbac-policy.csv
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/service/policy-builder.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: lgtm

#1230 fix(orchestrator): decommission the ProcessInstance.lastUpdate field
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-common/src/models.ts
  plugins/orchestrator/src/__fixtures__/fakeLongProcessInstanceList.ts
  plugins/orchestrator/src/__fixtures__/fakeProcessInstance.ts
Labels: approved, lgtm

#1182 feat(orchestrator): add OpenAPI v2 implementations
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
  plugins/orchestrator-backend/src/service/api/test-utils.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.test.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/openapitools.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/.openapi-generator-ignore
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/.openapi-generator/FILES
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/.openapi-generator/VERSION
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator-common/src/openapi/types.ts
Labels: approved, lgtm

#1229 fix(rbac): add test selectors
  packages/backend/package.json
  plugins/rbac/src/components/RolesList/DeleteRoleDialog.tsx
  yarn.lock
Labels: approved, lgtm

#1203 fix(rbac): reduce the catalog calls when build graph
  plugins/rbac-backend/src/file-permissions/csv.test.ts
  plugins/rbac-backend/src/role-manager/ancestor-search-memo.ts
  plugins/rbac-backend/src/role-manager/role-list.ts
  plugins/rbac-backend/src/role-manager/role-manager.test.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: approved, lgtm

#1178 feat(rbac): backend part - store role description to the database
  plugins/rbac-backend/migrations/20231212224526_migrations.js
  plugins/rbac-backend/migrations/20231221113214_migrations.js
  plugins/rbac-backend/migrations/20240201144429_migrations.js
  plugins/rbac-backend/src/database/policy-metadata-storage.test.ts
  plugins/rbac-backend/src/database/role-metadata.test.ts
  plugins/rbac-backend/src/database/role-metadata.ts
  plugins/rbac-backend/src/file-permissions/csv.ts
  plugins/rbac-backend/src/helper.test.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/enforcer.delegate.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-common/src/types.ts
Labels: lgtm

#1233 fix(orchestrator): implementation of getWorkflowById (v2)
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
Labels: approved, lgtm

#1223 fix(kubernetes-actions): support adding labels while creating namespace
  plugins/kubernetes-actions/README.md
  plugins/kubernetes-actions/examples/templates/01-kubernetes-template.yaml
  plugins/kubernetes-actions/src/actions/createKubernetesNamespace.test.ts
  plugins/kubernetes-actions/src/actions/createKubernetesNamespace.ts
Labels: approved, lgtm

#1238 chore(docs): update contributing guide to include pre-commit hook
  CONTRIBUTING.md
Labels: approved, lgtm

#1242 fix(orchestrator): minor improvements and fixes
  plugins/orchestrator-backend/src/service/CloudEventService.ts
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/JiraService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator-common/src/constants.ts
Labels: approved, lgtm

#1243 fix(rbac): fix labels and dropdowns in dark theme by aligning/downgrading components to MUI v4
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesForm.tsx
  plugins/rbac/src/components/CreateRole/PermissionPoliciesFormRow.tsx
  plugins/rbac/src/components/CreateRole/PoliciesCheckboxGroup.tsx
  plugins/rbac/src/components/CreateRole/ReviewStep.tsx
  plugins/rbac/src/components/RolesList/RolesListToolbar.tsx
  plugins/rbac/src/components/SnackbarAlert.tsx
Labels: kind/bug, approved, lgtm

#1249 test(web-terminal): fixes Terminal load test
  plugins/web-terminal/src/components/TerminalComponent/TerminalComponent.test.tsx
Labels: approved, lgtm

#991 docs(matomo-plugin): fix config example and replace GA with Matomo
  plugins/analytics-module-matomo/README.md
Labels: approved, lgtm

#1252 fix(orchestrator): improvements to backend services
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/Helper.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/router.ts
Labels: approved, lgtm

#1239 feat(orchestrator): display a alert dialog when the user fails to abort a running workflow
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
Labels: approved, lgtm

#1206 feat(rbac): save and display role description in the frontend
  plugins/rbac/src/components/CreateRole/EditRolePage.tsx
  plugins/rbac/src/components/RoleOverview/AboutCard.test.tsx
  plugins/rbac/src/components/RoleOverview/AboutCard.tsx
  plugins/rbac/src/components/RoleOverview/RoleOverviewPage.tsx
  plugins/rbac/src/hooks/useRole.test.ts
  plugins/rbac/src/hooks/useRole.ts
  plugins/rbac/src/hooks/useRoles.ts
  plugins/rbac/src/hooks/useSelectedMembers.test.ts
  plugins/rbac/src/hooks/useSelectedMembers.ts
  plugins/rbac/src/utils/create-role-utils.test.ts
  plugins/rbac/src/utils/create-role-utils.ts
Labels: approved, lgtm

#1231 feat(notifications): export Backstage plugin intsead of module
  plugins/notifications-backend/package.json
  plugins/notifications-backend/src/alpha.ts
  plugins/notifications-backend/src/index.ts
  plugins/notifications-backend/src/module.ts
  plugins/notifications-backend/src/plugin.ts
  plugins/notifications-backend/src/service/types.ts
Labels: approved, lgtm

#1270 fix(orchestrator): warn "unknown format X ignored in schema at path Y"
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/service/router.ts
Labels: approved, lgtm

#1256 fix(rbac): fixed autocomplete text input behavior on clear
  plugins/rbac/src/components/CreateRole/AddMembersForm.tsx
Labels: approved, lgtm

#1232 fix(notifications): bug flpath-901 spelling messageID
  plugins/notifications-backend/README.md
Labels: approved, lgtm

#1282 fix(orchestrator): remove date-time format from spec
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
Labels: approved, lgtm

#1283 fix(orchestrator): workflowId parameter wrongly parsed in getWorkflowOverviewById (v2)
  plugins/orchestrator-backend/src/service/router.ts
Labels: approved, lgtm

#1275 fix(notifications): add dynamicPluginInstaller
  plugins/notifications-backend/package.json
Labels: approved, lgtm

#1277 fix(orchestrator): handle nullable start/state properties of process instance
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/models.ts
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowInstanceStatusIndicator.tsx
  plugins/orchestrator/src/components/WorkflowProgressNode.tsx
  plugins/orchestrator/src/components/WorkflowProgressNodeModel.ts
  plugins/orchestrator/src/components/WorkflowRunDetail.ts
  plugins/orchestrator/src/hooks/useWorkflowInstanceStatusColors.ts
Labels: approved, lgtm

#1289 fix(orchestrator): regenerate Open API with new instance state
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/openapi/openapi.yaml
Labels: approved, lgtm

#1273 fix(notifications): rhidp-1210 Unable to get group notifications
  plugins/notifications-backend/src/service/handlers.ts
Labels: approved, lgtm

#1285 fix(rbac): improve error handling in retrieving permission metadata.
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
Labels: approved, lgtm

#1292 fix(orchestrator): clean up the plugin code
  plugins/orchestrator-backend/dev/index.ts
  plugins/orchestrator-backend/src/OrchestratorPlugin.ts
  plugins/orchestrator-backend/src/alpha.ts
  plugins/orchestrator-backend/src/dynamic/alpha.ts
  plugins/orchestrator-backend/src/dynamic/index.ts
  plugins/orchestrator-backend/src/index.ts
  plugins/orchestrator-backend/src/module/OrchestratorModuleEntityProvider.ts
  plugins/orchestrator-backend/src/module/index.ts
  plugins/orchestrator-backend/src/provider/OrchestratorEntityProvider.ts
  plugins/orchestrator-backend/src/provider/index.ts
  plugins/orchestrator-backend/src/routerWrapper/index.ts
  plugins/orchestrator-backend/src/service/DataInputSchemaService.test.ts
  plugins/orchestrator-backend/src/service/DataInputSchemaService.ts
  plugins/orchestrator-backend/src/service/OpenApiService.ts
  plugins/orchestrator-backend/src/service/WorkflowService.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.test.ts
  plugins/orchestrator-backend/src/service/api/mapping/V2Mappings.ts
  plugins/orchestrator-backend/src/service/api/test-utils.ts
  plugins/orchestrator-backend/src/service/api/v1.ts
  plugins/orchestrator-backend/src/service/api/v2.test.ts
  plugins/orchestrator-backend/src/service/api/v2.ts
  plugins/orchestrator-backend/src/service/openapi-template.json
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator-common/src/QueryParams.ts
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/constants.ts
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator-common/src/openapi/types.ts
  plugins/orchestrator-common/src/types.ts
  plugins/orchestrator/README.md
  plugins/orchestrator/src/__fixtures__/fakeFeatureFlagsApi.ts
  plugins/orchestrator/src/__fixtures__/fakeSpecs.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowSpecs.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/api/OrchestratorClient.ts
  plugins/orchestrator/src/api/api.ts
  plugins/orchestrator/src/components/CreateWorkflowPage.tsx
  plugins/orchestrator/src/components/EditWorkflowDialog.tsx
  plugins/orchestrator/src/components/NewWorkflowViewerPage.tsx
  plugins/orchestrator/src/components/OrchestratorPage.stories.tsx
  plugins/orchestrator/src/components/Router.tsx
  plugins/orchestrator/src/components/ScaffolderTemplateCard/OrchestratorScaffolderTemplateCard.tsx
  plugins/orchestrator/src/components/ScaffolderTemplateCard/index.ts
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.stories.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
  plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx
  plugins/orchestrator/src/components/WorkflowEditor/channel/WorkflowEditorLanguageService.ts
  plugins/orchestrator/src/components/WorkflowInstancePage.stories.tsx
  plugins/orchestrator/src/components/WorkflowInstancePageContent.tsx
  plugins/orchestrator/src/components/WorkflowsTabContent.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
  plugins/orchestrator/src/index.ts
  plugins/orchestrator/src/plugin.ts
  plugins/orchestrator/src/routes.ts
Labels: approved, lgtm

#1268 docs(rbac): update to the rbac documentation
  plugins/rbac-backend/README.md
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/docs/permissions.md
Labels: approved, lgtm

#1293 fix(rbac): improve error handling in retrieving permission metadata.
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
Labels: approved, lgtm

#1290 fix(orchestrator): refactor 500 response to use ErrorResponse object
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
  plugins/orchestrator-common/src/auto-generated/api/definition.ts
  plugins/orchestrator-common/src/auto-generated/api/models/schema.ts
  plugins/orchestrator-common/src/auto-generated/docs/index.adoc/index.adoc
  plugins/orchestrator-common/src/openapi/openapi.yaml
  plugins/orchestrator-common/src/openapi/types.ts
Labels: approved, lgtm
