Repository janus-idp/backstage-plugins, pull requests merged in 2024-06, with the labels that each got.

#1754 chore(orchestrator): add missing dev dependencies
  plugins/orchestrator-common/package.json
  plugins/orchestrator-common/scripts/openapi.sh
Labels: lgtm

#1728 fix(rbac): add proper empty page for RBAC plugin
  plugins/rbac/src/components/Router.test.tsx
  plugins/rbac/src/components/Router.tsx
Labels: approved, lgtm

#1730 fix(audit-log): deep copy objects passed into audit logger so redactor will not modify objects and remove `auditErrorLog` function
  plugins/audit-log-node/README.md
  plugins/audit-log-node/package.json
  plugins/audit-log-node/src/DefaultAuditLogger.test.ts
  plugins/audit-log-node/src/DefaultAuditLogger.ts
  plugins/audit-log-node/src/types.ts
  plugins/catalog-backend-module-scaffolder-relation-processor/package.json
Labels: approved, lgtm

#1757 fix(rbac): add support for scaling
  plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
  plugins/rbac-backend/src/database/casbin-adapter-factory.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/role-manager/member-list.test.ts
  plugins/rbac-backend/src/role-manager/member-list.ts
  plugins/rbac-backend/src/role-manager/role-list.test.ts
  plugins/rbac-backend/src/role-manager/role-list.ts
  plugins/rbac-backend/src/role-manager/role-manager.test.ts
  plugins/rbac-backend/src/role-manager/role-manager.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policy-builder.ts
Labels: approved, lgtm

#1714 fix(rbac): fix role list view permission policies column value
  plugins/rbac/src/components/RbacPage.test.tsx
  plugins/rbac/src/components/RolesList/RolesList.test.tsx
  plugins/rbac/src/components/RolesList/RolesList.tsx
  plugins/rbac/src/hooks/useRoles.test.ts
  plugins/rbac/src/hooks/useRoles.ts
Labels: approved, lgtm

#1781 fix(rbac): fix handling condition action conflicts
  plugins/rbac-backend/src/database/conditional-storage.ts
  plugins/rbac-backend/src/database/conditional.storage.test.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
Labels: approved, lgtm

#1726 feat(rbac): add audit log for RBAC backend
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/logger/customLogger.ts
  packages/backend/src/logger/index.ts
  plugins/rbac-backend/docs/audit-log.md
  plugins/rbac-backend/package.json
  plugins/rbac-backend/src/audit-log/audit-logger.ts
  plugins/rbac-backend/src/audit-log/rest-errors-interceptor.ts
  plugins/rbac-backend/src/database/role-metadata.test.ts
  plugins/rbac-backend/src/database/role-metadata.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.test.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/helper.test.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/enforcer-delegate.test.ts
  plugins/rbac-backend/src/service/enforcer-delegate.ts
  plugins/rbac-backend/src/service/permission-policy.test.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
  plugins/rbac-backend/src/service/policy-builder.ts
  plugins/rbac-backend/src/validation/policies-validation.test.ts
  plugins/rbac-common/src/types.ts
Labels: approved, lgtm

#1787 feat: switch defaults of the `--embed-as-dependencies` and `in-place` options.
  packages/cli/src/commands/index.ts
  yarn.lock
Labels: approved, lgtm

#1789 feat(rbac): add type checks with generics for audit log
  plugins/audit-log-node/src/DefaultAuditLogger.ts
  plugins/audit-log-node/src/types.ts
  plugins/rbac-backend/src/audit-log/audit-logger.ts
  plugins/rbac-backend/src/file-permissions/csv-file-watcher.ts
  plugins/rbac-backend/src/helper.ts
  plugins/rbac-backend/src/service/permission-policy.ts
  plugins/rbac-backend/src/service/policies-rest-api.ts
Labels: approved, lgtm

#1786 fix(kiali): sanitize input
  plugins/kiali-backend/src/service/router.test.ts
  plugins/kiali/src/components/DebugInformation/DebugInformation.tsx
  plugins/kiali/src/utils/Common.ts
Labels: lgtm

#1720 docs(kiali): update development doc
  plugins/kiali/DEVELOPMENT.md
Labels: lgtm

#1793 fix(kiali): remove debug window
  plugins/kiali/src/components/DebugInformation/DebugInformation.tsx
  plugins/kiali/src/pages/Kiali/Header/HelpKiali.tsx
  plugins/kiali/src/utils/Common.ts
Labels: lgtm

#1797 chore: align up playwright version in plugins and skip failed tests temporarily
  plugins/argocd/package.json
  plugins/bulk-import/package.json
  plugins/quay/package.json
  plugins/quay/tests/quay.spec.ts
  plugins/rbac/package.json
  plugins/tekton/package.json
  yarn.lock
Labels: approved, lgtm

#1798 fix(feedback): update EntityPage component
  plugins/feedback/src/components/CreateFeedbackModal/CreateFeedbackModal.tsx
  plugins/feedback/src/components/EntityFeedbackPage/EntityFeedbackPage.tsx
Labels: lgtm

#1800 fix(topology): remove check for catalog entity permission
  plugins/topology/package.json
  plugins/topology/src/components/Topology/TopologyViewWorkloadComponent.tsx
Labels: approved, lgtm

#1801 fix(kiali): fix dev links
  plugins/kiali/dev/MockProvider.tsx
  plugins/kiali/dev/index.tsx
  plugins/kiali/src/pages/AppDetails/AppDetailsPage.tsx
  plugins/kiali/src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiTabs.tsx
  plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceDetailsPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  plugins/kiali/src/routes.ts
Labels: lgtm

#1804 fix(orchestrator): fix error handling in case data index failed to start
  plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
Labels: lgtm

#1805 fix(orchestrator): fix error handling in case data index failed to start
  plugins/orchestrator-backend/src/service/OrchestratorService.test.ts
  plugins/orchestrator-backend/src/service/OrchestratorService.ts
Labels: lgtm

#1809 fix(feedback): fixed feedback backend plugin crashing
  plugins/feedback-backend/config.d.ts
  plugins/feedback-backend/src/service/emails.ts
  plugins/feedback-backend/src/service/router.ts
Labels: approved, lgtm

#1810 fix(cli): fix the removal of type definitions by `export-dynamic`.
  packages/cli/src/commands/export-dynamic-plugin/backend-embed-as-code.ts
Labels: approved, lgtm, do-not-merge/hold

#1811 fix: missing postversion script is several plugins and missing turbo dependency
  plugins/feedback-backend/dist-dynamic/package.json
  plugins/feedback-backend/package.json
  plugins/kiali-backend/dist-dynamic/package.json
  plugins/kiali-backend/package.json
  plugins/kubernetes-actions/dist-dynamic/package.json
  plugins/kubernetes-actions/package.json
  plugins/nexus-repository-manager/turbo.json
  plugins/scaffolder-annotator-action/dist-dynamic/package.json
  plugins/scaffolder-annotator-action/package.json
  plugins/servicenow-actions/turbo.json
  turbo.json
Labels: approved, lgtm

#1822 fix(matomo): add default export for new backend system
  plugins/matomo-backend/dist-dynamic/package.json
  plugins/matomo-backend/dist-dynamic/yarn.lock
  plugins/matomo-backend/package.json
  plugins/matomo-backend/src/dynamic/index.ts
  plugins/matomo-backend/src/index.ts
  plugins/matomo/package.json
  plugins/orchestrator/src/components/WorkflowEditor/WorkflowEditor.tsx
Labels: lgtm

#1824 fix(orchestrator): change log level of cache messages to be debug
  plugins/orchestrator-backend/src/service/WorkflowCacheService.ts
Labels: lgtm

#1825 feat(keycloak): expose keycloak user/group transformer extension point
  plugins/keycloak-backend/README.md
  plugins/keycloak-backend/src/extensions.ts
  plugins/keycloak-backend/src/index.ts
  plugins/keycloak-backend/src/module/catalogModuleKeycloakEntityProvider.ts
Labels: approved, lgtm

#1821 feat(kiali): resources card test coverage
  plugins/kiali/src/components/Health/HealthIndicator.tsx
  plugins/kiali/src/config/KialiIcon.tsx
  plugins/kiali/src/dynamic/EntityKialiResourcesCard.tsx
  plugins/kiali/tests/entityResources.spec.ts
Labels: lgtm

#1826 feat(bulk-import): update bulk import icon
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/src/components/BulkImportIcon.tsx
  plugins/bulk-import/src/images/BulkImportIcon-White.svg
  plugins/bulk-import/src/utils/icons.ts
Labels: approved, lgtm

#1829 feat(kiali): add banner to warn for tech preview windows
  plugins/kiali/src/components/Banners/TechPreviewWarning.tsx
  plugins/kiali/src/components/Router.tsx
Labels: lgtm

#1834 fix(argocd): hide commit section for helm based applications
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycle.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleCard.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/DeploymentLifecycleDrawer.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycle.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleCard.test.tsx
  plugins/argocd/src/components/DeploymentLifeCycle/__tests__/DeploymentLifecycleDrawer.test.tsx
  plugins/argocd/src/types.ts
Labels: approved, lgtm, plugin/argocd

#1827 feat(rbac): show total no. of rules in review and create step
  plugins/rbac/src/components/CreateRole/ReviewStep.tsx
  plugins/rbac/src/components/CreateRole/ReviewStepTable.tsx
  plugins/rbac/src/components/CreateRole/SelectedPermissionPoliciesColumn.tsx
  plugins/rbac/src/utils/create-role-utils.ts
Labels: approved, lgtm

#1541 feat(bulk-import): preview catalog-info.yaml on a side-panel
  plugins/bulk-import/README.md
  plugins/bulk-import/dev/index.tsx
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesDrawer.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesForm.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesFormFooter.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesPage.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.test.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/AddRepositoriesTableToolbar.tsx
  plugins/bulk-import/src/components/AddRepositories/CatalogInfoStatus.tsx
  plugins/bulk-import/src/components/AddRepositories/OrganizationColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/OrganizationTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/ReposSelectDrawerColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/RepositoriesColumnHeader.ts
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/bulk-import/src/components/AddRepositories/RepositoryTableRow.tsx
  plugins/bulk-import/src/components/AddRepositories/mockData.ts
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.test.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequests.tsx
  plugins/bulk-import/src/mocks/mockData.ts
  plugins/bulk-import/src/mocks/mockEntities.ts
  plugins/bulk-import/src/plugin.test.ts
  plugins/bulk-import/src/plugin.test.tsx
  plugins/bulk-import/src/types.ts
  plugins/bulk-import/src/utils/repository-utils.test.tsx
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
  yarn.lock
Labels: approved, lgtm

#1835 feat(kiali): include Kiali external URL as a parameter
  plugins/kiali-backend/app-config.janus-idp.yaml
  plugins/kiali-backend/config.d.ts
  plugins/kiali-backend/src/clients/KialiAPIConnector.test.ts
  plugins/kiali-backend/src/clients/fetch.test.ts
  plugins/kiali-backend/src/service/config.test.ts
  plugins/kiali-backend/src/service/config.ts
  plugins/kiali-backend/src/service/router.ts
  plugins/kiali/src/components/About/AboutUIModal.tsx
  plugins/kiali/src/components/DetailDescription/DetailDescription.tsx
  plugins/kiali/src/components/Label/Labels.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadsDescription.tsx
  plugins/kiali/src/types/StatusState.ts
  plugins/kiali/tests/entityResources.spec.ts
Labels: lgtm

#1840 chore(deps): regenerate yarn.lock to update ws
  plugins/kubernetes-actions/dist-dynamic/yarn.lock
  plugins/ocm-backend/dist-dynamic/yarn.lock
  yarn.lock
Labels: approved, lgtm

#1818 feat(orchestrator): disable buttons based on permissions
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator/docs/Permissions.md
  plugins/orchestrator/src/components/WorkflowDefinitionViewerPage/WorkflowDefinitionViewerPage.tsx
  plugins/orchestrator/src/components/WorkflowInstancePage.tsx
  plugins/orchestrator/src/components/WorkflowsTable.tsx
Labels: lgtm

#1790 feat(kiali): add tests for the overview page
  plugins/kiali/dev/__fixtures__/general/istioValidations.json
  plugins/kiali/dev/__fixtures__/namespaces/travel-agency/health/app.json
  plugins/kiali/dev/__fixtures__/namespaces/travel-control/health/app.json
  plugins/kiali/src/components/About/AboutUIModal.tsx
  plugins/kiali/src/components/MessageCenter/AlertDrawer.tsx
  plugins/kiali/src/components/MessageCenter/AlertDrawerGroup.tsx
  plugins/kiali/src/components/MessageCenter/AlertDrawerMessage.tsx
  plugins/kiali/src/components/MessageCenter/MessageCenter.tsx
  plugins/kiali/src/components/Validations/ValidationSummary.tsx
  plugins/kiali/src/pages/Kiali/Header/HelpKiali.tsx
  plugins/kiali/src/pages/Kiali/Header/KialiHeader.tsx
  plugins/kiali/src/pages/Kiali/Header/NamespaceSelector.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/NamespaceLabels.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/OverviewCard.tsx
  plugins/kiali/src/pages/Overview/OverviewStatus.tsx
  plugins/kiali/tests/kialiHelper.ts
  plugins/kiali/tests/kialiPage.spec.ts
Labels: lgtm

#1832 docs(keycloak-backend): update keycloak documentation
  plugins/keycloak-backend/README.md
Labels: approved, lgtm

#1572 feat(bulk-import): add repo row actions
  plugins/bulk-import/package.json
  plugins/bulk-import/src/components/AddRepositories/RepositoriesTable.tsx
  plugins/bulk-import/src/components/BulkImportPage.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewFile.tsx
  plugins/bulk-import/src/components/PreviewFile/PreviewPullRequest.tsx
  plugins/bulk-import/src/components/Repositories/DeleteRepository.tsx
  plugins/bulk-import/src/components/Repositories/DeleteRepositoryDialog.tsx
  plugins/bulk-import/src/components/Repositories/EditCatalogInfo.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.test.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesList.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListColumns.tsx
  plugins/bulk-import/src/components/Repositories/RepositoriesListForm.tsx
  plugins/bulk-import/src/components/Repositories/SyncRepository.tsx
  plugins/bulk-import/src/types.ts
  plugins/bulk-import/src/utils/repository-utils.tsx
  plugins/bulk-import/tests/bulkImport.spec.ts
  yarn.lock
Labels: approved, lgtm

#1839 feat(kiali): changes to Kiali 1.86
  plugins/kiali-backend/src/clients/KialiAPIConnector.test.ts
  plugins/kiali-backend/src/kiali_supported.json
  plugins/kiali-backend/src/service/router.test.ts
  plugins/kiali/dev/MockProvider.tsx
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/apps.json
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/appsHealth.json
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/services.json
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/servicesHealth.json
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/workloads.json
  plugins/kiali/dev/__fixtures__/clusters/kubernetes/workloadsHealth.json
  plugins/kiali/dev/__fixtures__/general/istioConfig.json
  plugins/kiali/dev/__fixtures__/index.ts
  plugins/kiali/src/config/Config.ts
  plugins/kiali/src/pages/AppList/AppListClass.tsx
  plugins/kiali/src/pages/AppList/AppListPage.tsx
  plugins/kiali/src/pages/IstioConfigList/IstioConfigListPage.tsx
  plugins/kiali/src/pages/Overview/NamespaceInfo.ts
  plugins/kiali/src/pages/Overview/OverviewCard/NamespaceStatus.tsx
  plugins/kiali/src/pages/Overview/OverviewCard/OverviewCard.tsx
  plugins/kiali/src/pages/Overview/OverviewPage.tsx
  plugins/kiali/src/pages/ServiceDetails/ServiceDetailsPage.tsx
  plugins/kiali/src/pages/ServiceList/ServiceListPage.tsx
  plugins/kiali/src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  plugins/kiali/src/pages/WorkloadList/WorkloadListPage.tsx
  plugins/kiali/src/services/Api.ts
  plugins/kiali/src/types/AppList.ts
  plugins/kiali/src/types/Health.ts
  plugins/kiali/src/types/IstioConfigList.ts
  plugins/kiali/src/types/ServiceList.ts
  plugins/kiali/src/types/Workload.ts
Labels: lgtm

#1833 feat(orchestrator): remove unneeded orchestrator jira integration and endpoint
  plugins/orchestrator-backend/src/service/CloudEventService.ts
  plugins/orchestrator-backend/src/service/DevModeService.ts
  plugins/orchestrator-backend/src/service/JiraService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowOverviewList.ts
Labels: lgtm

#1850 feat(orchestrator): fix build failure from #1833
  plugins/orchestrator-backend/src/service/router.ts
Labels: lgtm

#1841 fix(rbac): casbinDBAdapterFactory supporting postgres schema configuration
  plugins/rbac-backend/src/database/casbin-adapter-factory.test.ts
  plugins/rbac-backend/src/database/casbin-adapter-factory.ts
Labels: approved, lgtm

#1795 fix(rbac): correct plugin ID matching to permission policy
  plugins/rbac-backend/docs/apis.md
  plugins/rbac-backend/src/audit-log/audit-logger.ts
  plugins/rbac-backend/src/service/plugin-endpoint.test.ts
  plugins/rbac-backend/src/service/plugin-endpoints.ts
  plugins/rbac-backend/src/service/policies-rest-api.test.ts
  plugins/rbac-common/src/types.ts
  plugins/rbac/dev/index.tsx
  plugins/rbac/src/__fixtures__/mockPermissionPolicies.ts
  plugins/rbac/src/api/RBACBackendClient.ts
  plugins/rbac/src/utils/create-role-utils.test.ts
  plugins/rbac/src/utils/create-role-utils.ts
  plugins/rbac/src/utils/rbac-utils.ts
Labels: approved, lgtm
